//! Cross-language CLOB book-root parity (Stage 2, proof-carrying orderbook).
//!
//! The shared crate's `ClobBookV1::state_root` must equal Python
//! `src/state/clob_book.py::ClobBook.state_root` for EVERY fixture case --
//! byte-for-byte. This is what lets the eventual RISC0 guest prove the ACTUAL
//! ledger book root with no encoder-equivalence obligation. Fixture:
//! `shared/src/clob_book_roots_v1.json` (regenerated by
//! `tools/gen_clob_book_root_fixture.py`, kept current by
//! `tests/core/test_clob_book_root_fixture.py`).
//!
//! Lives in the CLI crate because the no_std shared crate has no JSON parser;
//! this test does NOT touch `main.rs`.

use tau_state_proof_risc0_shared::clob::{ClobBookV1, ClobOrderV1};

fn hexstr(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}

#[test]
fn clob_book_root_matches_python_byte_for_byte() {
    let fixture = include_str!("../../shared/src/clob_book_roots_v1.json");
    let v: serde_json::Value = serde_json::from_str(fixture).expect("fixture is valid JSON");
    let cases = v["cases"].as_array().expect("cases array");
    assert!(cases.len() >= 7, "fixture corpus too small");

    for case in cases {
        let mut orders = Vec::new();
        for o in case["orders"].as_array().expect("orders array") {
            orders.push(ClobOrderV1 {
                side_code: o["side_code"].as_u64().expect("side_code") as u8,
                price_q_per_base: o["price_q_per_base"].as_u64().expect("price"),
                base_qty: o["base_qty"].as_u64().expect("base_qty"),
                sequence: o["sequence"].as_u64().expect("sequence"),
                order_id: o["order_id"].as_str().expect("order_id").to_string(),
                owner: o["owner"].as_str().expect("owner").to_string(),
            });
        }
        let book = ClobBookV1::new(
            case["base_asset"].as_str().expect("base_asset").to_string(),
            case["quote_asset"].as_str().expect("quote_asset").to_string(),
            orders,
        );
        let root = book.state_root().expect("state_root");
        assert_eq!(
            hexstr(&root),
            case["state_root"].as_str().expect("state_root hex"),
            "book root mismatch for case {}",
            case["name"]
        );
    }
}
