from __future__ import annotations

import importlib.util
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location(
    "check_python_hash_locks", ROOT / "tools/check_python_hash_locks.py"
)
assert SPEC is not None and SPEC.loader is not None
check_python_hash_locks = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = check_python_hash_locks
SPEC.loader.exec_module(check_python_hash_locks)


def test_repo_python_hash_lock_audit_passes() -> None:
    report = check_python_hash_locks.check_python_hash_locks(ROOT)

    assert report["ok"], report["findings"]
    assert report["root_dependency_commands"] > 0
    assert {entry["path"] for entry in report["lockfiles"]} == {
        "requirements-core.lock.txt",
        "requirements-agents.lock.txt",
        "requirements-dev.lock.txt",
    }
    assert all(entry["packages"] > 0 for entry in report["lockfiles"])
    assert all(entry["hashes"] >= entry["packages"] for entry in report["lockfiles"])
    assert (
        report["pip_install_commands"]
        == report["root_dependency_commands"]
        + report["hash_locked_non_root_commands"]
        + report["allowlisted_unhashed_install_commands"]
    )
    hash_locked_non_root_paths = {
        entry["path"]
        for entry in report["install_surfaces"]
        if entry["hash_locked_non_root_commands"]
    }
    assert hash_locked_non_root_paths == {"tools/install_python_hash_locked_deps.sh"}
    allowlisted_paths = {
        entry["path"]
        for entry in report["install_surfaces"]
        if entry["allowlisted_unhashed_install_commands"]
    }
    expected_allowlisted_paths = {
        "docs/tau_testnet_local_node.md",
        "tools/README.md",
        "tools/gpu_env_check.py",
        "tools/run_local_tau_node_container.sh",
        "tools/run_tau_testnet_local_smoke.sh",
    }
    if (ROOT / "tools/runpod_esso.py").is_file():
        expected_allowlisted_paths.add("tools/runpod_esso.py")
    assert expected_allowlisted_paths <= allowlisted_paths


def test_lockfile_requirement_without_hash_is_rejected(tmp_path: Path) -> None:
    lock = tmp_path / "requirements-core.lock.txt"
    lock.write_text(
        "\n".join(
            (
                "#",
                "# This file is autogenerated by pip-compile",
                "# by the following command:",
                "#",
                "#    pip-compile --generate-hashes --output-file=requirements-core.lock.txt requirements-core.txt",
                "#",
                "example==1.0",
            )
        ),
        encoding="utf-8",
    )

    report = check_python_hash_locks.audit_lockfile(lock, root=tmp_path)

    assert not report["ok"]
    assert report["findings"][0]["code"] == "missing_hash"


def test_lockfile_live_include_is_rejected(tmp_path: Path) -> None:
    lock = tmp_path / "requirements-core.lock.txt"
    lock.write_text(
        "\n".join(
            (
                "#",
                "# This file is autogenerated by pip-compile",
                "# by the following command:",
                "#",
                "#    pip-compile --generate-hashes --output-file=requirements-core.lock.txt requirements-core.txt",
                "#",
                "-r requirements-core.txt",
            )
        ),
        encoding="utf-8",
    )

    report = check_python_hash_locks.audit_lockfile(lock, root=tmp_path)

    assert not report["ok"]
    assert report["findings"][0]["code"] == "live_include_in_lockfile"


def test_unhashed_root_lock_install_is_rejected(tmp_path: Path) -> None:
    script = tmp_path / "install.sh"
    script.write_text(
        "python -m pip install -r requirements-core.lock.txt\n",
        encoding="utf-8",
    )

    report = check_python_hash_locks.audit_install_surface(script, root=tmp_path)

    assert not report["ok"]
    assert report["findings"][0]["code"] == "missing_require_hashes"


def test_multiline_hashed_root_lock_install_is_accepted(tmp_path: Path) -> None:
    script = tmp_path / "install.sh"
    script.write_text(
        "python -m pip install --require-hashes \\\n"
        "  -r requirements-dev.lock.txt\n",
        encoding="utf-8",
    )

    report = check_python_hash_locks.audit_install_surface(script, root=tmp_path)

    assert report["ok"], report["findings"]
    assert report["root_dependency_commands"] == 1


def test_unhashed_lock_variable_install_is_rejected(tmp_path: Path) -> None:
    script = tmp_path / "install.sh"
    script.write_text(
        'DEV_LOCK="${ROOT_DIR}/requirements-dev.lock.txt"\n'
        'python -m pip install -r "$DEV_LOCK"\n',
        encoding="utf-8",
    )

    report = check_python_hash_locks.audit_install_surface(script, root=tmp_path)

    assert not report["ok"]
    assert report["findings"][0]["code"] == "missing_require_hashes"


def test_unlocked_root_manifest_install_is_rejected(tmp_path: Path) -> None:
    script = tmp_path / "install.sh"
    script.write_text(
        "python -m pip install --require-hashes -r requirements-core.txt\n",
        encoding="utf-8",
    )

    report = check_python_hash_locks.audit_install_surface(script, root=tmp_path)

    assert not report["ok"]
    assert report["findings"][0]["code"] == "unlocked_root_requirements_install"


def test_untracked_unhashed_non_root_install_is_rejected(tmp_path: Path) -> None:
    script = tmp_path / "install.sh"
    script.write_text(
        "python -m pip install requests==2.32.3\n",
        encoding="utf-8",
    )

    report = check_python_hash_locks.audit_install_surface(script, root=tmp_path)

    assert not report["ok"]
    assert report["findings"][0]["code"] == "untracked_unhashed_python_install"


def test_hash_locked_variable_install_is_counted_as_covered(tmp_path: Path) -> None:
    script = tmp_path / "install.sh"
    script.write_text(
        'lock_file="requirements-dev.lock.txt"\n'
        'python -m pip install --require-hashes -r "$ROOT_DIR/$lock_file"\n',
        encoding="utf-8",
    )

    report = check_python_hash_locks.audit_install_surface(script, root=tmp_path)

    assert report["ok"], report["findings"]
    assert report["pip_install_commands"] == 1
    assert report["root_dependency_commands"] == 0
    assert report["hash_locked_non_root_commands"] == 1


def test_missing_supported_root_lock_install_command_is_rejected(tmp_path: Path) -> None:
    for name in (
        "requirements-core.lock.txt",
        "requirements-agents.lock.txt",
        "requirements-dev.lock.txt",
    ):
        lock = tmp_path / name
        lock.write_text(
            "\n".join(
                (
                    "#",
                    "# This file is autogenerated by pip-compile",
                    "# by the following command:",
                    "#",
                    f"#    pip-compile --generate-hashes --output-file={name} {name.removesuffix('.lock.txt')}.txt",
                    "#",
                    "example==1.0 \\",
                    "    --hash=sha256:" + "a" * 64,
                )
            ),
            encoding="utf-8",
        )

    report = check_python_hash_locks.check_python_hash_locks(tmp_path)

    assert not report["ok"]
    assert report["root_dependency_commands"] == 0
    assert report["findings"] == [
        {
            "path": "install-surfaces",
            "line": 0,
            "code": "missing_hashed_root_install_command",
            "message": "supported install surfaces must include at least one root lockfile install command",
        }
    ]
