[package]
name = "zenodex-zrpf-risc0-spot-value-leaf-v4"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
risc0-zkvm = { version = "=3.0.5", default-features = false }
zenodex-zrpf-protocol-v3 = { path = "../../../zrpf_protocol/protocol", default-features = false }
zenodex-zrpf-risc0-value-node-shared = { path = "../../value_node_shared", default-features = false }

[[bin]]
name = "zenodex-zrpf-risc0-spot-value-leaf-v4"
path = "src/main.rs"
test = false
bench = false
