from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Any

# Allow `python3 tools/bva/gen_pytest_cases.py ...` from repo root.
_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from tools.bva.mine_bva import _eval_label, _load_scenario, mine_dynamic_boundaries  # noqa: E402
from tools.bva.mine_bva import mine_mcmc_boundaries  # noqa: E402


def _as_py(obj: Any) -> str:
    """Pretty-ish Python literal for small JSON-like objects."""
    return json.dumps(obj, sort_keys=True).replace("true", "True").replace("false", "False").replace("null", "None")


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Generate pytest param cases from BVA boundary mining results.")
    ap.add_argument("--scenario", required=True, help="Path to a BVA scenario module.")
    ap.add_argument("--boundaries", default="", help="Path to boundary JSON (if omitted, mines on the fly).")
    ap.add_argument(
        "--source",
        choices=["dynamic", "mcmc", "both"],
        default="dynamic",
        help="Where to pull cases from: dynamic (axis scans), mcmc (global MCMC axis boundaries), or both.",
    )
    ap.add_argument(
        "--include-mcmc-pairs",
        action="store_true",
        help="Also include raw opposite-label pair endpoints from MCMC as cases (not BVA triples).",
    )
    ap.add_argument("--only-param", default="", help="Filter cases to this param name.")
    ap.add_argument("--limit", type=int, default=24, help="Max cases to emit.")
    ap.add_argument("--emit", choices=["kwargs", "label"], default="kwargs", help="Emit kwargs+expected_label tuples.")
    args = ap.parse_args(argv)

    s = _load_scenario(args.scenario)

    if str(args.boundaries or "").strip():
        data = json.loads(open(args.boundaries, encoding="utf-8").read())
    else:
        data = mine_dynamic_boundaries(s)
        if args.source in ("mcmc", "both"):
            # Keep generator runs small; for larger discovery, mine once via mine_bva.py.
            data["mcmc"] = mine_mcmc_boundaries(s, chains=4, steps=256, max_pairs=12)

    dyn: list[dict[str, Any]] = []
    if args.source in ("dynamic", "both"):
        d0 = data.get("dynamic_boundaries", [])
        if not isinstance(d0, list):
            raise SystemExit("invalid boundaries JSON: missing dynamic_boundaries list")
        dyn.extend([x for x in d0 if isinstance(x, dict)])
    if args.source in ("mcmc", "both"):
        m = data.get("mcmc", {})
        if isinstance(m, dict):
            d1 = m.get("axis_boundaries", [])
            if isinstance(d1, list):
                dyn.extend([x for x in d1 if isinstance(x, dict)])
            if args.include_mcmc_pairs:
                pc = m.get("pair_cases", [])
                if isinstance(pc, list) and pc:
                    dyn.append({"param": "__mcmc_pairs__", "cases": pc})

    only = str(args.only_param or "").strip()
    cases: list[tuple[dict[str, Any], Any, str]] = []
    seen: set[str] = set()
    for g in dyn:
        if not isinstance(g, dict):
            continue
        if only and g.get("param") != only:
            continue
        for c in g.get("cases", []):
            if not isinstance(c, dict):
                continue
            kwargs = c.get("params", {})
            if not isinstance(kwargs, dict):
                continue
            k = json.dumps(kwargs, sort_keys=True, default=str)
            if k in seen:
                continue
            seen.add(k)
            lbl = _eval_label(s, kwargs=dict(kwargs))
            reason = str(c.get("reason", "")).strip() or "boundary-mined case"
            cases.append((dict(kwargs), lbl, reason))
            if int(args.limit) > 0 and len(cases) >= int(args.limit):
                break
        if int(args.limit) > 0 and len(cases) >= int(args.limit):
            break

    print("# Generated by tools/bva/gen_pytest_cases.py")
    print("import pytest")
    print()
    print("@pytest.mark.parametrize(")
    print('    "kwargs,expected_label,reason",')
    print("    [")
    for kw, lbl, reason in cases:
        print(f"        ({_as_py(kw)}, {_as_py(lbl)}, {_as_py(reason)}),")
    print("    ],")
    print(")")
    print("def test_bva_mined(kwargs, expected_label, reason):")
    print("    _ = reason")
    print("    # TODO: replace this generic assertion with field-level assertions for readability.")
    print("    from tools.bva.mine_bva import _load_scenario as _ls, _eval_label as _el")
    print(f"    s = _ls({_as_py(os.path.abspath(args.scenario))})")
    print("    assert _el(s, kwargs=kwargs) == expected_label")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
