export const ORACLE_NETWORK_SUMMARY = [
  {
    id: 'accepted_reads',
    label: 'Accepted Reads',
    value: '1,248',
    delta: '+12.5%',
    tone: 'positive',
    detail: 'O3+ receipts replayable',
  },
  {
    id: 'active_feeds',
    label: 'Active Feeds',
    value: '38',
    delta: '+2.7%',
    tone: 'positive',
    detail: '5 critical profiles',
  },
  {
    id: 'reporters',
    label: 'Reporters',
    value: '128',
    delta: '+4.3%',
    tone: 'positive',
    detail: '112 active, 16 pending',
  },
  {
    id: 'o3_floor',
    label: 'Critical Evidence',
    value: 'O3',
    delta: 'floor',
    tone: 'neutral',
    detail: 'No O2 critical reads',
  },
  {
    id: 'open_disputes',
    label: 'Open Disputes',
    value: '3',
    delta: '-25%',
    tone: 'warning',
    detail: '2 quarantined feeds',
  },
  {
    id: 'network_health',
    label: 'Network Health',
    value: '98.7%',
    delta: 'Excellent',
    tone: 'positive',
    detail: 'All replay gates green',
  },
];

export const ORACLE_FEEDS = [
  {
    id: 'tasset0_zdex_spot',
    feed: 'TASSET0/ZDEX',
    domain: 'Spot',
    queryId: 'qry_tasset0_zdex_spot_v1',
    value: '2.0000',
    unit: 'ZDEX',
    reference: '2.00 ZDEX',
    change24h: '+0.03%',
    evidenceClass: 'O3',
    freshness: '1 epoch',
    status: 'fresh',
    confidence: '+/-0.0064',
    deviationBps: 28,
    receiptId: 'rct_a1b2...9f7e',
    actionUse: 'swap, zUSD, perps',
  },
  {
    id: 'zdex_tasset0_spot',
    feed: 'ZDEX/TASSET0',
    domain: 'Spot',
    queryId: 'qry_zdex_tasset0_spot_v1',
    value: '0.5000',
    unit: 'TASSET0',
    reference: '0.50 TASSET0',
    change24h: '+0.03%',
    evidenceClass: 'O3',
    freshness: '2 epochs',
    status: 'fresh',
    confidence: '+/-0.0011',
    deviationBps: 8,
    receiptId: 'rct_c31a...4d02',
    actionUse: 'swap, treasury',
  },
  {
    id: 'tasset1_zdex_perps',
    feed: 'TASSET1/ZDEX',
    domain: 'Perps index',
    queryId: 'qry_tasset1_zdex_perps_v1',
    value: '1.0000',
    unit: 'ZDEX',
    reference: '1.00 ZDEX',
    change24h: '-1.23%',
    evidenceClass: 'O4',
    freshness: '1 epoch',
    status: 'fresh',
    confidence: '+/-12.45',
    deviationBps: 32,
    receiptId: 'rct_f07b...8a21',
    actionUse: 'perps settlement',
  },
  {
    id: 'zusd_usd_stable',
    feed: 'zUSD/USD',
    domain: 'Stablecoin',
    queryId: 'qry_zusd_usd_stability_v1',
    value: '1.0011',
    unit: 'USD',
    reference: '$1.00',
    change24h: '+0.01%',
    evidenceClass: 'O3',
    freshness: '2 epochs',
    status: 'fresh',
    confidence: '+/-0.0009',
    deviationBps: 11,
    receiptId: 'rct_771e...65c9',
    actionUse: 'zUSD redemption',
  },
  {
    id: 'rwa_real_estate',
    feed: 'RWA/zUSD',
    domain: 'RWA policy draft',
    queryId: 'qry_rwa_usdc_beta_v1',
    value: '102.80',
    unit: 'zUSD',
    reference: '$102.80',
    change24h: '+0.00%',
    evidenceClass: 'O2',
    freshness: '18 epochs',
    status: 'devnet-only',
    confidence: '+/-4.25',
    deviationBps: 415,
    receiptId: 'rct_dev0...991a',
    actionUse: 'blocked for critical use',
  },
  {
    id: 'stock_beta',
    feed: 'AAPL/USD',
    domain: 'Stock policy draft',
    queryId: 'qry_aapl_usd_beta_v1',
    value: '181.22',
    unit: 'USD',
    reference: '$181.22',
    change24h: '+0.44%',
    evidenceClass: 'O2',
    freshness: 'market close',
    status: 'high-uncertainty',
    confidence: '+/-2.18',
    deviationBps: 121,
    receiptId: 'rct_dev1...27ab',
    actionUse: 'quote preview only',
  },
];

export const ORACLE_HEALTH_METRICS = [
  { id: 'uptime', label: 'Uptime', value: 99.2, status: 'healthy' },
  { id: 'data_quality', label: 'Data Quality', value: 98.1, status: 'healthy' },
  { id: 'timeliness', label: 'Timeliness', value: 99.0, status: 'healthy' },
  { id: 'source_diversity', label: 'Source Diversity', value: 97.9, status: 'healthy' },
  { id: 'economic_security', label: 'Economic Security', value: 99.1, status: 'healthy' },
];

export const ORACLE_REPORTERS = [
  {
    id: 'zeno1...7k6p',
    status: 'active',
    bond: '12,500 ZENO',
    requiredBond: '10,000 ZENO',
    accepted: 812,
    missed: 2,
    rewards: '1,284.6 ZENO',
    controlGroup: 'cg-north-01',
  },
  {
    id: 'zeno1...3m9x',
    status: 'quarantined',
    bond: '15,000 ZENO',
    requiredBond: '10,000 ZENO',
    accepted: 611,
    missed: 8,
    rewards: '884.2 ZENO',
    controlGroup: 'cg-east-04',
  },
  {
    id: 'zeno1...8n4q',
    status: 'active',
    bond: '22,000 ZENO',
    requiredBond: '10,000 ZENO',
    accepted: 947,
    missed: 1,
    rewards: '1,903.7 ZENO',
    controlGroup: 'cg-west-02',
  },
];

export const ORACLE_DISPUTES = [
  {
    id: 'dsp_tasset0_001',
    feed: 'TASSET0/ZDEX',
    target: 'rct_a1b2...9f7e',
    reporter: 'zeno1...7k6p',
    bond: '1,000 ZENO',
    age: '2h',
    status: 'quarantined',
  },
  {
    id: 'dsp_tasset1_004',
    feed: 'TASSET1/ZDEX',
    target: 'rct_f07b...8a21',
    reporter: 'zeno1...3m9x',
    bond: '2,500 ZENO',
    age: '5h',
    status: 'open',
  },
  {
    id: 'dsp_tzeno_008',
    feed: 'TZENO/ZDEX',
    target: 'rct_2c45...8n4q',
    reporter: 'zeno1...8n4q',
    bond: '5,000 ZENO',
    age: '1d',
    status: 'appeal',
  },
];

export const ORACLE_REWARDS = [
  {
    id: 'zeno1...7k6p',
    reporter: 'zeno1...7k6p',
    pending: '384.6 ZENO',
    paid: '900.0 ZENO',
    slashed: '0.0 ZENO',
    accepted: 812,
    status: 'payable',
  },
  {
    id: 'zeno1...3m9x',
    reporter: 'zeno1...3m9x',
    pending: '0.0 ZENO',
    paid: '884.2 ZENO',
    slashed: '2,500.0 ZENO',
    accepted: 611,
    status: 'quarantined',
  },
  {
    id: 'zeno1...8n4q',
    reporter: 'zeno1...8n4q',
    pending: '503.7 ZENO',
    paid: '1,400.0 ZENO',
    slashed: '0.0 ZENO',
    accepted: 947,
    status: 'payable',
  },
];

export const ORACLE_EVENTS = [
  {
    id: 'evt_001',
    kind: 'Accepted Read',
    feed: 'TASSET1/ZDEX',
    detail: 'O4 evidence',
    age: '12s ago',
    tone: 'success',
  },
  {
    id: 'evt_002',
    kind: 'Report Submitted',
    feed: 'ZDEX/TASSET0',
    detail: 'sequence 24119',
    age: '18s ago',
    tone: 'info',
  },
  {
    id: 'evt_003',
    kind: 'Dispute Opened',
    feed: 'TASSET0/ZDEX',
    detail: 'bond 1,000 ZENO',
    age: '2h ago',
    tone: 'warning',
  },
  {
    id: 'evt_004',
    kind: 'Reporter Slashed',
    feed: 'BTC/ZDEX',
    detail: 'slash 2,500 ZENO',
    age: '5h ago',
    tone: 'danger',
  },
  {
    id: 'evt_005',
    kind: 'Fee Distributed',
    feed: 'Rewards',
    detail: '12 reporters paid',
    age: '6h ago',
    tone: 'proof',
  },
];

export const ORACLE_EVIDENCE_DISTRIBUTION = [
  { id: 'O3', label: 'O3 Robust aggregate', percent: 24, count: 300 },
  { id: 'O4', label: 'O4 Proof-backed', percent: 38, count: 474 },
  { id: 'O5', label: 'O5 Cross-checked', percent: 38, count: 474 },
];

export const ORACLE_CONSUMER_PROFILES = [
  {
    id: 'zusd_mint',
    label: 'zUSD mint',
    evidenceFloor: 'O3',
    maxFreshness: '2 epochs',
    status: 'ready',
    valueBinding: 'value_e8 required',
  },
  {
    id: 'perps_settlement',
    label: 'Perps settlement',
    evidenceFloor: 'O3',
    maxFreshness: '1 epoch',
    status: 'ready',
    valueBinding: 'price history bound',
  },
  {
    id: 'trigger_orders',
    label: 'Trigger orders',
    evidenceFloor: 'O3',
    maxFreshness: '1 epoch',
    status: 'pending',
    valueBinding: 'adapter in progress',
  },
  {
    id: 'rwa_beta',
    label: 'RWA beta',
    evidenceFloor: 'O4',
    maxFreshness: 'policy-specific',
    status: 'blocked',
    valueBinding: 'registry review required',
  },
];

export const ORACLE_SYSTEM_SERVICES = [
  { id: 'receipt_verifier', label: 'Receipt Verifier', status: 'Operational' },
  { id: 'report_admission', label: 'Report Admission', status: 'Operational' },
  { id: 'aggregation_engine', label: 'Aggregation Engine', status: 'Operational' },
  { id: 'dispute_system', label: 'Dispute System', status: 'Operational' },
  { id: 'proof_generation', label: 'Proof Generation', status: 'Roadmap' },
];
