from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class _Finding:
    path: str
    line: int
    col: int
    kind: str
    detail: str


class _FloatUsageVisitor(ast.NodeVisitor):
    """
    Functional core policy:
    - No float literals
    - No `float(...)` casts
    - No true-division (`/`) on the functional core path
    - No float-returning `math.*` calls (allow `gcd`, `isqrt`)
    """

    _MATH_ALLOWED = {"gcd", "isqrt"}
    _MATH_BANNED_IMPORTS = {"sqrt", "log", "log10", "log2", "exp", "pow", "sin", "cos", "tan"}

    def __init__(self, path: Path) -> None:
        super().__init__()
        self._path = path
        self.findings: list[_Finding] = []

    def _add(self, node: ast.AST, *, kind: str, detail: str) -> None:
        lineno = getattr(node, "lineno", 1)
        col = getattr(node, "col_offset", 0)
        self.findings.append(
            _Finding(
                path=str(self._path),
                line=int(lineno),
                col=int(col) + 1,
                kind=str(kind),
                detail=str(detail),
            )
        )

    def visit_Constant(self, node: ast.Constant) -> None:  # noqa: N802 (ast API)
        if isinstance(node.value, float):
            self._add(node, kind="float_literal", detail=repr(node.value))
        super().generic_visit(node)

    def visit_BinOp(self, node: ast.BinOp) -> None:  # noqa: N802 (ast API)
        if isinstance(node.op, ast.Div):
            self._add(node, kind="true_division", detail="use // or cross-multiply rationals")
        super().generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:  # noqa: N802 (ast API)
        # float(...)
        if isinstance(node.func, ast.Name) and node.func.id == "float":
            self._add(node, kind="float_cast", detail="float(...) is disallowed in src/core and src/state")

        # math.<fn>(...)
        if isinstance(node.func, ast.Attribute) and isinstance(node.func.value, ast.Name) and node.func.value.id == "math":
            fn = str(node.func.attr)
            if fn not in self._MATH_ALLOWED:
                self._add(node, kind="math_call", detail=f"math.{fn}(...) is disallowed (float-returning or non-core)")

        super().generic_visit(node)

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:  # noqa: N802 (ast API)
        if node.module == "math":
            for alias in node.names:
                name = str(alias.name)
                if name in self._MATH_BANNED_IMPORTS:
                    self._add(node, kind="math_import", detail=f"from math import {name} is disallowed")
        super().generic_visit(node)


def _iter_py_files(root: Path) -> list[Path]:
    out: list[Path] = []
    for p in root.rglob("*.py"):
        # Ignore autogenerated/bytecode dirs just in case.
        if "__pycache__" in p.parts:
            continue
        out.append(p)
    out.sort()
    return out


def test_functional_core_has_no_floats_or_true_division() -> None:
    repo_root = Path(__file__).resolve().parents[2]
    roots = (
        repo_root / "src" / "core",
        repo_root / "src" / "state",
    )

    findings: list[_Finding] = []
    for r in roots:
        assert r.is_dir(), f"missing directory: {r}"
        for path in _iter_py_files(r):
            try:
                src = path.read_text(encoding="utf-8")
            except Exception as exc:
                raise AssertionError(f"failed to read {path}: {exc}") from exc
            try:
                tree = ast.parse(src, filename=str(path))
            except SyntaxError as exc:
                raise AssertionError(f"failed to parse {path}: {exc}") from exc
            v = _FloatUsageVisitor(path)
            v.visit(tree)
            findings.extend(v.findings)

    if findings:
        msg_lines = ["functional core float policy violated:"]
        for f in findings:
            msg_lines.append(f"- {f.path}:{f.line}:{f.col} {f.kind}: {f.detail}")
        raise AssertionError("\n".join(msg_lines))

