//! Epoch-machine transition core (Rust mirror of `gov_epoch.py`).
//!
//! The verdict kernel (`lib.rs`) answers "is this revision admissible?"; this
//! module ports the MACHINE around it: propose → timelock/veto window →
//! all-or-nothing apply through every tier in the FIXED precedence, charter
//! renew/revoke, the freeze interlock, and the trajectory bookkeeping
//! (cooldowns, window-rolled drift budgets, the aggregate epoch budget).
//!
//! DESIGN: invalid states are unrepresentable. Surfaces are an enum (no
//! unknown-surface paths), the state is fixed-size arrays over `u16` (no maps,
//! no heap in the core), flags are real bools. The entire hostile-object tier
//! of `gov_epoch.py` — exact-type guards, use-time re-validation, snapshot
//! discipline, canonical-tuple checks — exists because Python cannot make
//! those states unrepresentable; here the type system carries it, and what
//! remains to verify is the TRANSITION LOGIC itself.
//!
//! CORE / RECEIPT SPLIT: `*_core` functions are pure, allocation-free, and
//! return `(State, Code, Option<Surface>)` — these are the Kani targets
//! (sha256 is excluded from the symbolic path by construction). The public
//! wrappers add the canonical params digests and produce `EpochReceipt`,
//! mirroring `gov_epoch.GovReceipt` field-for-field; the cross-language
//! scenario fixture (generated by replaying `gov_epoch.py`) binds the two
//! implementations transition-by-transition.
//!
//! SEMANTIC PARITY NOTES (each mirrors a documented gov_epoch.py rule):
//! - apply precedence: no_pending → frozen → charter → timelock(pending KEPT)
//!   → cooldown (touched surfaces in declaration order) → pointwise gates
//!   (scalars fee/funding/whale, then router AS A UNIT, then collateral AS A
//!   UNIT) → window-rolled drift budgets (touched order) → aggregate epoch
//!   budget → apply. Pending is KEPT only on the timelock reject.
//! - the lane's `approved` IS charter validity (checked before the gates run).
//! - a window only rolls when `now − window_start ≥ DRIFT_WINDOW_EPOCHS` with
//!   the wrap-guard; a "future" window_start never rolls (fail-closed), and
//!   roll state commits ONLY on a full apply.
//! - Python's TypeError/ValueError paths for hostile/malformed objects are
//!   unrepresentable here; the two value-domain errors that remain
//!   (charter ttl, delta magnitude) are `EpochError` — `Err` corresponds to
//!   "gov_epoch raises", reject receipts to "well-formed but inadmissible".

use crate::{
    charter_ok, collateral_ratio_revision_ok, cooldown_ok, drift_budget_ok, epoch_budget_ok,
    fee_revision_ok, funding_rate_revision_ok, router_revision_ok, whale_defense_revision_ok,
    CHARTER_TTL_MAX, DRIFT_WINDOW_EPOCHS, EPOCH_MOVEMENT_BUDGET, FEE_STEP_BPS, FUNDING_STEP_BPS,
    GOV_COOLDOWN_EPOCHS, MIN_DELAY, RATIO_STEP_BPS, SPLIT_STEP_BPS, WHALE_STEP_BPS,
};
use sha2::{Digest, Sha256};

pub const SURFACE_COUNT: usize = 9;

/// The nine governed surfaces, in `gov_epoch.ALL_SURFACES` DECLARATION order
/// (scalars, router shares, collateral pair) — this is the order the cooldown
/// and drift loops consult, so first-failing-surface receipts match Python.
/// (The canonical digest uses SORTED name order; see `params_digest_arr`.)
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Surface {
    FeeBps = 0,
    FundingCapBps = 1,
    RedeemStakerBps = 2,
    BuyburnBps = 3,
    StakersBps = 4,
    ReserveBps = 5,
    HostsBps = 6,
    McrBps = 7,
    CcrBps = 8,
}

pub const SURFACES: [Surface; SURFACE_COUNT] = [
    Surface::FeeBps,
    Surface::FundingCapBps,
    Surface::RedeemStakerBps,
    Surface::BuyburnBps,
    Surface::StakersBps,
    Surface::ReserveBps,
    Surface::HostsBps,
    Surface::McrBps,
    Surface::CcrBps,
];

impl Surface {
    pub fn name(self) -> &'static str {
        match self {
            Surface::FeeBps => "fee_bps",
            Surface::FundingCapBps => "funding_cap_bps",
            Surface::RedeemStakerBps => "redeem_staker_bps",
            Surface::BuyburnBps => "buyburn_bps",
            Surface::StakersBps => "stakers_bps",
            Surface::ReserveBps => "reserve_bps",
            Surface::HostsBps => "hosts_bps",
            Surface::McrBps => "mcr_bps",
            Surface::CcrBps => "ccr_bps",
        }
    }

    pub fn from_name(name: &str) -> Option<Surface> {
        SURFACES.iter().copied().find(|s| s.name() == name)
    }

    /// Per-surface window drift budget (mirrors gov_gate.DRIFT_BUDGET_BPS:
    /// 3 pointwise steps per window).
    pub fn drift_budget(self) -> u16 {
        match self {
            Surface::FeeBps => 3 * FEE_STEP_BPS,
            Surface::FundingCapBps => 3 * FUNDING_STEP_BPS,
            Surface::RedeemStakerBps => 3 * WHALE_STEP_BPS,
            Surface::BuyburnBps | Surface::StakersBps | Surface::ReserveBps
            | Surface::HostsBps => 3 * SPLIT_STEP_BPS,
            Surface::McrBps | Surface::CcrBps => 3 * RATIO_STEP_BPS,
        }
    }
}

const SCALARS: [Surface; 3] = [Surface::FeeBps, Surface::FundingCapBps, Surface::RedeemStakerBps];
const ROUTER: [Surface; 4] =
    [Surface::BuyburnBps, Surface::StakersBps, Surface::ReserveBps, Surface::HostsBps];
const COLLATERAL: [Surface; 2] = [Surface::McrBps, Surface::CcrBps];

/// Per-surface trajectory bookkeeping (mirrors gov_epoch.SurfaceTraj).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct SurfaceTraj {
    pub last_revision_epoch: u16,
    pub window_start_epoch: u16,
    pub drift_used: u16,
}

/// Standing approval (mirrors gov_epoch.Charter; the policy pin is boundary
/// metadata carried for receipts/audit — charter VALIDITY ignores it).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Charter {
    pub granted_epoch: u16,
    pub ttl: u16,
    pub revoked: bool,
    pub policy_pin: [u8; 32],
}

/// A queued multi-surface action maturing in the timelock/veto window.
/// `touched[i]` gates whether `deltas[i]` is part of the action.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct PendingRevision {
    pub deltas: [i32; SURFACE_COUNT],
    pub touched: [bool; SURFACE_COUNT],
    pub proposed_epoch: u16,
}

impl PendingRevision {
    pub fn is_empty(&self) -> bool {
        !self.touched.iter().any(|&t| t)
    }
}

/// The governed envelope's committed state (mirrors gov_epoch.GovEpochState).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct EpochState {
    pub params: [u16; SURFACE_COUNT],
    pub traj: [SurfaceTraj; SURFACE_COUNT],
    pub charter: Option<Charter>,
    pub frozen: bool,
    pub pending: Option<PendingRevision>,
}

/// Stable receipt codes (mirrors the gov_epoch GOV_* string constants;
/// `as_str` is the cross-language wire form the fixture compares).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Code {
    OkProposed,
    OkApplied,
    OkVetoed,
    OkCharterRenewed,
    OkCharterRevoked,
    OkFrozenSet,
    RejNoPending,
    RejPendingExists,
    RejEmptyAction,
    RejFrozen,
    RejCharterInvalid,
    RejTimelock,
    RejCooldown,
    RejSurfaceGate,
    RejDriftBudget,
    RejEpochBudget,
    RejNoCharter,
}

impl Code {
    pub fn as_str(self) -> &'static str {
        match self {
            Code::OkProposed => "gov_ok_proposed",
            Code::OkApplied => "gov_ok_applied",
            Code::OkVetoed => "gov_ok_vetoed",
            Code::OkCharterRenewed => "gov_ok_charter_renewed",
            Code::OkCharterRevoked => "gov_ok_charter_revoked",
            Code::OkFrozenSet => "gov_ok_frozen_set",
            Code::RejNoPending => "gov_rej_no_pending",
            Code::RejPendingExists => "gov_rej_pending_exists",
            Code::RejEmptyAction => "gov_rej_empty_action",
            Code::RejFrozen => "gov_rej_frozen",
            Code::RejCharterInvalid => "gov_rej_charter_invalid",
            Code::RejTimelock => "gov_rej_timelock",
            Code::RejCooldown => "gov_rej_cooldown",
            Code::RejSurfaceGate => "gov_rej_surface_gate",
            Code::RejDriftBudget => "gov_rej_drift_budget",
            Code::RejEpochBudget => "gov_rej_epoch_budget",
            Code::RejNoCharter => "gov_rej_no_charter",
        }
    }
}

/// Reject-surface label: Python reports a SURFACE name for scalar/cooldown/
/// drift rejects but the GROUP name ("router"/"collateral") for unit rejects.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum RejectAt {
    Surface(Surface),
    Router,
    Collateral,
}

impl RejectAt {
    pub fn label(self) -> &'static str {
        match self {
            RejectAt::Surface(s) => s.name(),
            RejectAt::Router => "router",
            RejectAt::Collateral => "collateral",
        }
    }
}

/// "gov_epoch raises" equivalents — the only two value-domain errors the
/// typed core can still express.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum EpochError {
    /// renew_charter ttl outside [1, CHARTER_TTL_MAX] (no perpetual charter).
    TtlOutOfRange,
    /// a delta magnitude outside the bv[16] band (|d| > 0xFFFF).
    DeltaOutOfRange,
}

/// Canonical genesis (mirrors gov_epoch.genesis_state): autonomy DISABLED
/// (no charter — fail-closed), trajectory clocks start at `epoch`.
pub fn genesis_state(params: [u16; SURFACE_COUNT], epoch: u16) -> EpochState {
    EpochState {
        params,
        traj: [SurfaceTraj {
            last_revision_epoch: epoch,
            window_start_epoch: epoch,
            drift_used: 0,
        }; SURFACE_COUNT],
        charter: None,
        frozen: false,
        pending: None,
    }
}

fn charter_valid(state: &EpochState, now_epoch: u16) -> bool {
    match state.charter {
        None => false,
        Some(c) => charter_ok(c.revoked, c.granted_epoch, now_epoch, c.ttl),
    }
}

// ---------------------------------------------------------------------------
// Core transitions (pure, allocation-free — the Kani targets).
// ---------------------------------------------------------------------------

pub fn propose_revision_core(
    state: &EpochState,
    deltas: &[i32; SURFACE_COUNT],
    touched: &[bool; SURFACE_COUNT],
    now_epoch: u16,
) -> Result<(EpochState, Code), EpochError> {
    for i in 0..SURFACE_COUNT {
        if touched[i] && !(-(0xFFFF_i32)..=0xFFFF_i32).contains(&deltas[i]) {
            return Err(EpochError::DeltaOutOfRange);
        }
    }
    if state.frozen {
        return Ok((*state, Code::RejFrozen));
    }
    if state.pending.is_some() {
        return Ok((*state, Code::RejPendingExists));
    }
    if !charter_valid(state, now_epoch) {
        return Ok((*state, Code::RejCharterInvalid));
    }
    if !touched.iter().any(|&t| t) {
        return Ok((*state, Code::RejEmptyAction));
    }
    let mut clean = [0_i32; SURFACE_COUNT];
    for i in 0..SURFACE_COUNT {
        if touched[i] {
            clean[i] = deltas[i];
        }
    }
    let mut new = *state;
    new.pending = Some(PendingRevision {
        deltas: clean,
        touched: *touched,
        proposed_epoch: now_epoch,
    });
    Ok((new, Code::OkProposed))
}

pub fn veto_pending_core(state: &EpochState, _now_epoch: u16) -> (EpochState, Code) {
    // never gated: stopping is always safe (works frozen and unchartered)
    match state.pending {
        None => (*state, Code::RejNoPending),
        Some(_) => {
            let mut new = *state;
            new.pending = None;
            (new, Code::OkVetoed)
        }
    }
}

/// The apply pipeline. Returns the post-state, the code, and the
/// first-failing surface/group label where applicable.
pub fn apply_pending_core(
    state: &EpochState,
    now_epoch: u16,
) -> (EpochState, Code, Option<RejectAt>) {
    let pending = match state.pending {
        None => return (*state, Code::RejNoPending, None),
        Some(p) => p,
    };
    let cleared = {
        let mut s = *state;
        s.pending = None;
        s
    };
    if state.frozen {
        return (cleared, Code::RejFrozen, None);
    }
    if !charter_valid(state, now_epoch) {
        return (cleared, Code::RejCharterInvalid, None);
    }
    // timelock: pending KEPT (not yet mature — wait and retry)
    if !cooldown_ok(pending.proposed_epoch, now_epoch, MIN_DELAY) {
        return (*state, Code::RejTimelock, None);
    }
    // per-surface cooldown, declaration order
    for (i, s) in SURFACES.iter().enumerate() {
        if pending.touched[i]
            && !cooldown_ok(state.traj[i].last_revision_epoch, now_epoch, GOV_COOLDOWN_EPOCHS)
        {
            return (cleared, Code::RejCooldown, Some(RejectAt::Surface(*s)));
        }
    }

    // candidate next values (i64 to carry out-of-band candidates to the gates,
    // which reject them exactly as Python's domain guards do)
    let mut next = [0_i64; SURFACE_COUNT];
    for i in 0..SURFACE_COUNT {
        // |params| <= 0xFFFF and |delta| <= 0xFFFF: saturation is unreachable,
        // written saturating to satisfy the checked-arithmetic lint exactly.
        next[i] = i64::from(state.params[i])
            .saturating_add(if pending.touched[i] { i64::from(pending.deltas[i]) } else { 0 });
    }
    let in_band = |v: i64| -> Option<u16> { u16::try_from(v).ok() };

    // pointwise gates, the multi-surface order: scalars -> router unit -> collateral unit.
    // approved=True IS charter validity (established above); timelock re-checked by the
    // gates with the same subtraction-guard (already known to pass).
    let scalar_gate = |s: Surface, curr: u16, nxt: u16| -> bool {
        match s {
            Surface::FeeBps => {
                fee_revision_ok(true, true, pending.proposed_epoch, now_epoch, curr, nxt)
            }
            Surface::FundingCapBps => {
                funding_rate_revision_ok(true, true, pending.proposed_epoch, now_epoch, curr, nxt)
            }
            Surface::RedeemStakerBps => {
                whale_defense_revision_ok(true, true, pending.proposed_epoch, now_epoch, curr, nxt)
            }
            _ => false,
        }
    };
    for s in SCALARS {
        let i = s as usize;
        if pending.touched[i] {
            let ok = match in_band(next[i]) {
                Some(nxt) => scalar_gate(s, state.params[i], nxt),
                None => false, // Python: gate domain guard rejects the raw int
            };
            if !ok {
                return (cleared, Code::RejSurfaceGate, Some(RejectAt::Surface(s)));
            }
        }
    }
    if ROUTER.iter().any(|&s| pending.touched[s as usize]) {
        let nx: Option<[u16; 4]> = (|| {
            Some([
                in_band(next[Surface::BuyburnBps as usize])?,
                in_band(next[Surface::StakersBps as usize])?,
                in_band(next[Surface::ReserveBps as usize])?,
                in_band(next[Surface::HostsBps as usize])?,
            ])
        })();
        let ok = match nx {
            Some([b, st, r, h]) => router_revision_ok(
                true, true, pending.proposed_epoch, now_epoch,
                b, st, r, h,
                state.params[Surface::BuyburnBps as usize],
                state.params[Surface::StakersBps as usize],
                state.params[Surface::ReserveBps as usize],
                state.params[Surface::HostsBps as usize],
            ),
            None => false,
        };
        if !ok {
            return (cleared, Code::RejSurfaceGate, Some(RejectAt::Router));
        }
    }
    if COLLATERAL.iter().any(|&s| pending.touched[s as usize]) {
        let mcr_i = Surface::McrBps as usize;
        let ccr_i = Surface::CcrBps as usize;
        let ok = match (in_band(next[mcr_i]), in_band(next[ccr_i])) {
            (Some(mn), Some(cn)) => collateral_ratio_revision_ok(
                true, true, pending.proposed_epoch, now_epoch,
                state.params[mcr_i], mn, state.params[ccr_i], cn,
            ),
            _ => false,
        };
        if !ok {
            return (cleared, Code::RejSurfaceGate, Some(RejectAt::Collateral));
        }
    }

    // window-rolled drift budgets (touched order); roll commits ONLY on apply
    let mut rolled: [SurfaceTraj; SURFACE_COUNT] = state.traj;
    for (i, s) in SURFACES.iter().enumerate() {
        if !pending.touched[i] {
            continue;
        }
        let t = state.traj[i];
        // wrap-guarded roll; a "future" window_start never rolls (fail-closed)
        let fresh = now_epoch
            .checked_sub(t.window_start_epoch)
            .is_some_and(|age| age >= DRIFT_WINDOW_EPOCHS);
        let used = if fresh { 0 } else { t.drift_used };
        let start = if fresh { now_epoch } else { t.window_start_epoch };
        // gates passed => next[i] is in the surface band, hence in u16
        let nxt = match in_band(next[i]) {
            Some(v) => v,
            None => return (cleared, Code::RejDriftBudget, Some(RejectAt::Surface(*s))),
        };
        if !drift_budget_ok(state.params[i], nxt, used, s.drift_budget()) {
            return (cleared, Code::RejDriftBudget, Some(RejectAt::Surface(*s)));
        }
        let mag = pending.deltas[i].unsigned_abs().min(0xFFFF) as u16;
        rolled[i] = SurfaceTraj {
            last_revision_epoch: now_epoch,
            window_start_epoch: start,
            // admitted => mag <= budget - used <= 0xFFFF: no overflow
            drift_used: used.saturating_add(mag),
        };
    }

    // aggregate epoch budget over the three gate groups
    let group_sum = |members: &[Surface]| -> u16 {
        let mut acc: u32 = 0;
        for &s in members {
            let i = s as usize;
            if pending.touched[i] {
                acc = acc.saturating_add(pending.deltas[i].unsigned_abs().min(0xFFFF));
            }
        }
        // each group has <= 4 members of <= 0xFFFF; Python passes exact sums —
        // values above u16 would be rejected by epoch_budget_ok's domain in
        // Python (in_domain fails) => mirror by saturating into the reject
        u16::try_from(acc).unwrap_or(u16::MAX)
    };
    let ok = epoch_budget_ok(
        group_sum(&SCALARS),
        group_sum(&ROUTER),
        group_sum(&COLLATERAL),
        EPOCH_MOVEMENT_BUDGET,
    );
    if !ok {
        return (cleared, Code::RejEpochBudget, None);
    }

    // all tiers passed: commit params + trajectories, clear pending
    let mut new = *state;
    for i in 0..SURFACE_COUNT {
        if pending.touched[i] {
            // gates admitted => in band
            new.params[i] = in_band(next[i]).unwrap_or(new.params[i]);
            new.traj[i] = rolled[i];
        }
    }
    new.pending = None;
    (new, Code::OkApplied, None)
}

pub fn renew_charter_core(
    state: &EpochState,
    now_epoch: u16,
    ttl: u16,
    policy_pin: [u8; 32],
) -> Result<(EpochState, Code), EpochError> {
    if ttl == 0 || ttl > CHARTER_TTL_MAX {
        return Err(EpochError::TtlOutOfRange);
    }
    let mut new = *state;
    new.charter = Some(Charter { granted_epoch: now_epoch, ttl, revoked: false, policy_pin });
    Ok((new, Code::OkCharterRenewed))
}

pub fn revoke_charter_core(state: &EpochState, _now_epoch: u16) -> (EpochState, Code) {
    // never gated: stopping is always safe; idempotent
    match state.charter {
        None => (*state, Code::RejNoCharter),
        Some(c) => {
            let mut new = *state;
            new.charter = Some(Charter { revoked: true, ..c });
            (new, Code::OkCharterRevoked)
        }
    }
}

pub fn set_frozen_core(state: &EpochState, flag: bool, _now_epoch: u16) -> (EpochState, Code) {
    let mut new = *state;
    new.frozen = flag;
    (new, Code::OkFrozenSet)
}

// ---------------------------------------------------------------------------
// Receipt wrappers (digests live here, OUTSIDE the Kani-targeted core).
// ---------------------------------------------------------------------------

/// Canonical outcome of one transition (mirrors gov_epoch.GovReceipt).
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct EpochReceipt {
    pub code: Code,
    pub epoch: u16,
    pub surface: Option<&'static str>,
    pub digest_before: String,
    pub digest_after: String,
    pub policy_pin: Option<[u8; 32]>,
}

/// Canonical digest of a params array — byte-identical to
/// `gov_epoch.params_digest` (sorted name order, `[["k",v],...]`, no spaces).
pub fn params_digest_arr(params: &[u16; SURFACE_COUNT]) -> String {
    // sorted name order over the fixed surface set
    let mut order: [usize; SURFACE_COUNT] = [0, 1, 2, 3, 4, 5, 6, 7, 8];
    order.sort_by_key(|&i| SURFACES[i].name());
    let mut canonical = String::from("[");
    let mut first = true;
    for &i in &order {
        if !first {
            canonical.push(',');
        }
        first = false;
        canonical.push_str("[\"");
        canonical.push_str(SURFACES[i].name());
        canonical.push_str("\",");
        canonical.push_str(crate::itoa_u16(params[i]).as_str());
        canonical.push(']');
    }
    canonical.push(']');
    let mut hasher = Sha256::new();
    hasher.update(canonical.as_bytes());
    hex::encode(hasher.finalize())
}

fn pin_of(state: &EpochState) -> Option<[u8; 32]> {
    state.charter.map(|c| c.policy_pin)
}

fn receipt(
    code: Code,
    epoch: u16,
    surface: Option<RejectAt>,
    before: &EpochState,
    after: &EpochState,
    pin: Option<[u8; 32]>,
) -> EpochReceipt {
    EpochReceipt {
        code,
        epoch,
        surface: surface.map(RejectAt::label),
        digest_before: params_digest_arr(&before.params),
        digest_after: params_digest_arr(&after.params),
        policy_pin: pin,
    }
}

pub fn propose_revision(
    state: &EpochState,
    deltas: &[i32; SURFACE_COUNT],
    touched: &[bool; SURFACE_COUNT],
    now_epoch: u16,
) -> Result<(EpochState, EpochReceipt), EpochError> {
    let pin = pin_of(state);
    let (new, code) = propose_revision_core(state, deltas, touched, now_epoch)?;
    let r = receipt(code, now_epoch, None, state, &new, pin);
    Ok((new, r))
}

pub fn veto_pending(state: &EpochState, now_epoch: u16) -> (EpochState, EpochReceipt) {
    let pin = pin_of(state);
    let (new, code) = veto_pending_core(state, now_epoch);
    let r = receipt(code, now_epoch, None, state, &new, pin);
    (new, r)
}

pub fn apply_pending(state: &EpochState, now_epoch: u16) -> (EpochState, EpochReceipt) {
    let pin = pin_of(state);
    let (new, code, at) = apply_pending_core(state, now_epoch);
    let r = receipt(code, now_epoch, at, state, &new, pin);
    (new, r)
}

pub fn renew_charter(
    state: &EpochState,
    now_epoch: u16,
    ttl: u16,
    policy_pin: [u8; 32],
) -> Result<(EpochState, EpochReceipt), EpochError> {
    let (new, code) = renew_charter_core(state, now_epoch, ttl, policy_pin)?;
    // mirrors gov_epoch: the renewal receipt carries the NEW pin
    let r = receipt(code, now_epoch, None, state, &new, Some(policy_pin));
    Ok((new, r))
}

pub fn revoke_charter(state: &EpochState, now_epoch: u16) -> (EpochState, EpochReceipt) {
    let pin = pin_of(state);
    let (new, code) = revoke_charter_core(state, now_epoch);
    // mirrors gov_epoch: no-charter reject carries pin=None; revocation carries the pin
    let r = receipt(code, now_epoch, None, state, &new, if state.charter.is_some() { pin } else { None });
    (new, r)
}

pub fn set_frozen(state: &EpochState, flag: bool, now_epoch: u16) -> (EpochState, EpochReceipt) {
    let pin = pin_of(state);
    let (new, code) = set_frozen_core(state, flag, now_epoch);
    let r = receipt(code, now_epoch, None, state, &new, pin);
    (new, r)
}

// ---------------------------------------------------------------------------
// Unit teeth (the scenario fixture in tests/epoch_parity.rs is the real bind).
// ---------------------------------------------------------------------------
#[cfg(test)]
mod tests {
    use super::*;

    const GENESIS: [u16; SURFACE_COUNT] = [500, 100, 6000, 6000, 0, 2000, 2000, 11000, 15000];
    const PIN: [u8; 32] = [0xab; 32];

    fn chartered() -> EpochState {
        let s = genesis_state(GENESIS, 0);
        let (s, r) = renew_charter(&s, 0, 4096, PIN).unwrap();
        assert_eq!(r.code, Code::OkCharterRenewed);
        s
    }

    fn one(surface: Surface, d: i32) -> ([i32; SURFACE_COUNT], [bool; SURFACE_COUNT]) {
        let mut deltas = [0_i32; SURFACE_COUNT];
        let mut touched = [false; SURFACE_COUNT];
        deltas[surface as usize] = d;
        touched[surface as usize] = true;
        (deltas, touched)
    }

    #[test]
    fn genesis_is_fail_closed() {
        let s = genesis_state(GENESIS, 0);
        let (d, t) = one(Surface::FeeBps, 10);
        let (s2, r) = propose_revision(&s, &d, &t, 0).unwrap();
        assert_eq!(r.code, Code::RejCharterInvalid);
        assert_eq!(s2, s);
        assert_eq!(r.digest_before, r.digest_after);
    }

    #[test]
    fn walk_halts_at_drift_budget() {
        let mut s = chartered();
        let mut now: u16 = 0;
        let mut codes = vec![];
        for _ in 0..4 {
            let (d, t) = one(Surface::FeeBps, 50);
            let (s1, rp) = propose_revision(&s, &d, &t, now).unwrap();
            assert_eq!(rp.code, Code::OkProposed);
            now += GOV_COOLDOWN_EPOCHS;
            let (s2, ra) = apply_pending(&s1, now);
            codes.push(ra.code);
            s = s2;
        }
        assert_eq!(
            codes,
            vec![Code::OkApplied, Code::OkApplied, Code::OkApplied, Code::RejDriftBudget]
        );
        assert_eq!(s.params[Surface::FeeBps as usize], 650);
    }

    #[test]
    fn timelock_keeps_pending_cooldown_clears_it() {
        let s = chartered();
        let (d, t) = one(Surface::FeeBps, 50);
        let (s1, _) = propose_revision(&s, &d, &t, 0).unwrap();
        let (s2, r) = apply_pending(&s1, MIN_DELAY - 1);
        assert_eq!(r.code, Code::RejTimelock);
        assert!(s2.pending.is_some()); // KEPT
        let (s3, r2) = apply_pending(&s2, GOV_COOLDOWN_EPOCHS);
        assert_eq!(r2.code, Code::OkApplied);
        let (d2, t2) = one(Surface::FeeBps, 10);
        let (s4, _) = propose_revision(&s3, &d2, &t2, GOV_COOLDOWN_EPOCHS).unwrap();
        let (s5, r3) = apply_pending(&s4, GOV_COOLDOWN_EPOCHS + MIN_DELAY);
        assert_eq!(r3.code, Code::RejCooldown);
        assert_eq!(r3.surface, Some("fee_bps"));
        assert!(s5.pending.is_none()); // CLEARED
    }

    #[test]
    fn coordinated_walk_hits_epoch_budget() {
        let s = chartered();
        let deltas: [i32; SURFACE_COUNT] = [50, 25, 500, -500, 500, -500, 500, 1000, 1000];
        let touched = [true; SURFACE_COUNT];
        let (s1, rp) = propose_revision(&s, &deltas, &touched, 0).unwrap();
        assert_eq!(rp.code, Code::OkProposed);
        let (s2, r) = apply_pending(&s1, GOV_COOLDOWN_EPOCHS);
        assert_eq!(r.code, Code::RejEpochBudget);
        assert_eq!(s2.params, GENESIS); // all-or-nothing
    }

    #[test]
    fn veto_and_freeze_paths() {
        let s = chartered();
        let (d, t) = one(Surface::FeeBps, 50);
        let (s1, _) = propose_revision(&s, &d, &t, 0).unwrap();
        let (s2, _) = set_frozen(&s1, true, 1);
        let (s3, rv) = veto_pending(&s2, 2);
        assert_eq!(rv.code, Code::OkVetoed); // veto works while frozen
        let (_, ra) = apply_pending(&s3, GOV_COOLDOWN_EPOCHS);
        assert_eq!(ra.code, Code::RejNoPending);
    }

    #[test]
    fn digest_matches_lib_btreemap_encoder() {
        // the array encoder and the BTreeMap encoder must agree byte-for-byte
        let arr_digest = params_digest_arr(&GENESIS);
        let map: std::collections::BTreeMap<String, u16> = SURFACES
            .iter()
            .map(|s| (s.name().to_string(), GENESIS[*s as usize]))
            .collect();
        assert_eq!(arr_digest, crate::params_digest(&map).expect("exact surface set"));
    }
}

// ---------------------------------------------------------------------------
// Kani harnesses over the FULL symbolic state space (digest-free core only).
// Run: cargo kani -p zenodex-governance-gate
// ---------------------------------------------------------------------------
#[cfg(kani)]
mod verification {
    use super::*;

    fn any_state() -> EpochState {
        let mut params = [0_u16; SURFACE_COUNT];
        let mut traj = [SurfaceTraj {
            last_revision_epoch: 0,
            window_start_epoch: 0,
            drift_used: 0,
        }; SURFACE_COUNT];
        let mut i = 0;
        while i < SURFACE_COUNT {
            params[i] = kani::any();
            traj[i] = SurfaceTraj {
                last_revision_epoch: kani::any(),
                window_start_epoch: kani::any(),
                drift_used: kani::any(),
            };
            i += 1;
        }
        let charter = if kani::any() {
            Some(Charter {
                granted_epoch: kani::any(),
                ttl: kani::any(),
                revoked: kani::any(),
                policy_pin: [0_u8; 32], // pin is audit metadata; validity ignores it
            })
        } else {
            None
        };
        let pending = if kani::any() {
            let mut deltas = [0_i32; SURFACE_COUNT];
            let mut touched = [false; SURFACE_COUNT];
            let mut j = 0;
            while j < SURFACE_COUNT {
                let d: i32 = kani::any();
                kani::assume((-(0xFFFF_i32)..=0xFFFF_i32).contains(&d));
                deltas[j] = d;
                touched[j] = kani::any();
                j += 1;
            }
            Some(PendingRevision { deltas, touched, proposed_epoch: kani::any() })
        } else {
            None
        };
        EpochState { params, traj, charter, frozen: kani::any(), pending }
    }

    /// THE machine-level CBC property, over the whole bounded domain: any
    /// apply outcome other than OkApplied leaves params, trajectories,
    /// charter, and the freeze flag untouched (pending may clear by design).
    #[kani::proof]
    fn apply_reject_is_noop() {
        let s = any_state();
        let now: u16 = kani::any();
        let (post, code, _at) = apply_pending_core(&s, now);
        if code != Code::OkApplied {
            assert!(post.params == s.params);
            assert!(post.traj == s.traj);
            assert!(post.charter == s.charter);
            assert!(post.frozen == s.frozen);
        }
    }

    /// Pending lifecycle on apply: kept ONLY on the timelock reject; cleared
    /// on every other reject (when one existed); always cleared on apply.
    #[kani::proof]
    fn apply_pending_kept_vs_cleared() {
        let s = any_state();
        let now: u16 = kani::any();
        let (post, code, _at) = apply_pending_core(&s, now);
        match code {
            Code::RejNoPending => assert!(post.pending.is_none() && s.pending.is_none()),
            Code::RejTimelock => assert!(post.pending == s.pending),
            _ => assert!(post.pending.is_none()),
        }
    }

    /// Accept ⇒ authority invariants, for every touched surface: the timelock
    /// and per-surface cooldown held, the drift charge fits the window budget,
    /// and the bookkeeping is exactly the documented update.
    #[kani::proof]
    fn apply_accept_bookkeeping_and_bounds() {
        let s = any_state();
        let now: u16 = kani::any();
        let (post, code, _at) = apply_pending_core(&s, now);
        if code == Code::OkApplied {
            let p = s.pending.unwrap();
            assert!(post.pending.is_none());
            // timelock held (subtraction-guard form)
            assert!(now >= p.proposed_epoch && now - p.proposed_epoch >= MIN_DELAY);
            let mut i = 0;
            while i < SURFACE_COUNT {
                if p.touched[i] {
                    // cooldown held against the PRE-state trajectory
                    let last = s.traj[i].last_revision_epoch;
                    assert!(now >= last && now - last >= GOV_COOLDOWN_EPOCHS);
                    // drift charge within the window budget
                    assert!(post.traj[i].drift_used <= SURFACES[i].drift_budget());
                    assert!(post.traj[i].last_revision_epoch == now);
                    // the applied delta is exactly the pending delta
                    let next = i64::from(s.params[i]) + i64::from(p.deltas[i]);
                    assert!(i64::from(post.params[i]) == next);
                } else {
                    assert!(post.params[i] == s.params[i]);
                    assert!(post.traj[i] == s.traj[i]);
                }
                i += 1;
            }
        }
    }

    /// Accept ⇒ surface-band invariants: scalars inside their caps/steps, the
    /// router shares summing exactly to SPLIT_SUM when touched, the collateral
    /// pair ordered inside floor/ceiling.
    #[kani::proof]
    fn apply_accept_band_invariants() {
        let s = any_state();
        let now: u16 = kani::any();
        let (post, code, _at) = apply_pending_core(&s, now);
        if code == Code::OkApplied {
            let p = s.pending.unwrap();
            if p.touched[Surface::FeeBps as usize] {
                assert!(post.params[Surface::FeeBps as usize] <= crate::FEE_MAX_BPS);
            }
            if p.touched[Surface::FundingCapBps as usize] {
                assert!(post.params[Surface::FundingCapBps as usize] <= crate::FUNDING_CAP_MAX_BPS);
            }
            if p.touched[Surface::RedeemStakerBps as usize] {
                assert!(post.params[Surface::RedeemStakerBps as usize] <= crate::WHALE_STAKER_BPS_MAX);
            }
            let router_touched = p.touched[Surface::BuyburnBps as usize]
                || p.touched[Surface::StakersBps as usize]
                || p.touched[Surface::ReserveBps as usize]
                || p.touched[Surface::HostsBps as usize];
            if router_touched {
                let sum: u32 = u32::from(post.params[Surface::BuyburnBps as usize])
                    + u32::from(post.params[Surface::StakersBps as usize])
                    + u32::from(post.params[Surface::ReserveBps as usize])
                    + u32::from(post.params[Surface::HostsBps as usize]);
                assert!(sum == u32::from(crate::SPLIT_SUM));
            }
            let coll_touched =
                p.touched[Surface::McrBps as usize] || p.touched[Surface::CcrBps as usize];
            if coll_touched {
                let mcr = post.params[Surface::McrBps as usize];
                let ccr = post.params[Surface::CcrBps as usize];
                assert!(mcr >= crate::RATIO_MIN_BPS);
                assert!(ccr <= crate::RATIO_MAX_BPS);
                assert!(mcr <= ccr);
            }
        }
    }

    /// Accept ⇒ the standing approval really held at `now` (dead-man teeth):
    /// an apply can never fire revoked, expired, never-chartered, or frozen.
    #[kani::proof]
    fn apply_accept_requires_live_charter_and_thaw() {
        let s = any_state();
        let now: u16 = kani::any();
        let (_post, code, _at) = apply_pending_core(&s, now);
        if code == Code::OkApplied {
            assert!(!s.frozen);
            let c = s.charter.unwrap();
            assert!(!c.revoked);
            assert!(c.ttl <= CHARTER_TTL_MAX);
            assert!(now >= c.granted_epoch && now - c.granted_epoch < c.ttl);
        }
    }

    /// Precedence dominance pins: no-pending answers before any authority
    /// question; freeze answers before charter/timelock.
    #[kani::proof]
    fn apply_precedence_dominance() {
        let s = any_state();
        let now: u16 = kani::any();
        let (_post, code, _at) = apply_pending_core(&s, now);
        if s.pending.is_none() {
            assert!(code == Code::RejNoPending);
        } else if s.frozen {
            assert!(code == Code::RejFrozen);
        }
    }

    /// Propose: reject is a FULL no-op; accept changes ONLY pending, and the
    /// recorded action zeroes untouched deltas (no smuggled payload).
    #[kani::proof]
    fn propose_isolation() {
        let s = any_state();
        let now: u16 = kani::any();
        let mut deltas = [0_i32; SURFACE_COUNT];
        let mut touched = [false; SURFACE_COUNT];
        let mut i = 0;
        while i < SURFACE_COUNT {
            let d: i32 = kani::any();
            kani::assume((-(0xFFFF_i32)..=0xFFFF_i32).contains(&d));
            deltas[i] = d;
            touched[i] = kani::any();
            i += 1;
        }
        let (post, code) = match propose_revision_core(&s, &deltas, &touched, now) {
            Ok(v) => v,
            Err(_) => return, // magnitude guard: unreachable under the assume
        };
        if code == Code::OkProposed {
            assert!(post.params == s.params && post.traj == s.traj);
            assert!(post.charter == s.charter && post.frozen == s.frozen);
            let p = post.pending.unwrap();
            assert!(p.proposed_epoch == now);
            let mut j = 0;
            while j < SURFACE_COUNT {
                if p.touched[j] {
                    assert!(p.deltas[j] == deltas[j]);
                } else {
                    assert!(p.deltas[j] == 0);
                }
                j += 1;
            }
        } else {
            assert!(post == s);
        }
    }

    /// Veto / revoke / freeze field isolation: each transition touches exactly
    /// its own field, never the params or trajectories.
    #[kani::proof]
    fn stop_authorities_field_isolation() {
        let s = any_state();
        let now: u16 = kani::any();
        let (v, vcode) = veto_pending_core(&s, now);
        assert!(v.params == s.params && v.traj == s.traj && v.charter == s.charter);
        if vcode == Code::RejNoPending {
            assert!(v == s);
        } else {
            assert!(v.pending.is_none());
        }
        let (r, rcode) = revoke_charter_core(&s, now);
        assert!(r.params == s.params && r.traj == s.traj && r.pending == s.pending);
        if rcode == Code::OkCharterRevoked {
            assert!(r.charter.unwrap().revoked);
        } else {
            assert!(r == s);
        }
        let flag: bool = kani::any();
        let (f, _) = set_frozen_core(&s, flag, now);
        assert!(f.params == s.params && f.traj == s.traj);
        assert!(f.charter == s.charter && f.pending == s.pending);
        assert!(f.frozen == flag);
    }
}
