//! Stage 2 proof-carrying orderbook -- canonical CLOB book with a LEDGER-EXACT root.
//!
//! [`ClobBookV1::state_root`] reproduces `src/state/clob_book.py::ClobBook.state_root`
//! BYTE-FOR-BYTE by porting the ledger's OWN canonical encoders (encode_uvarint,
//! domain_sep_bytes, hex_to_bytes_fixed from `src/state/canonical.py`). So the
//! eventual RISC0 guest proves the ACTUAL ledger book root -- there is NO
//! encoder-equivalence obligation here (unlike the perps surface, whose guest
//! hashes in a private scheme). Cross-language parity is pinned by
//! `clob_book_roots_v1.json` (regenerated by `tools/gen_clob_book_root_fixture.py`,
//! kept current by `tests/core/test_clob_book_root_fixture.py`).
//!
//! Canonicalization trap (resolved): orders are stored in strict
//! `order_priority_key` order = (side_code, signed price_term [-price for BUY,
//! +price for SELL], sequence, order_id). The SORT uses the SIGNED term, but the
//! ENCODING uses the UNSIGNED `price_q_per_base`. Conflating them silently breaks
//! the root for BUY-heavy books only -- the parity corpus includes such a book.

use alloc::format;
use alloc::string::String;
use alloc::vec::Vec;
use sha2::{Digest, Sha256};

// --- canonical encoders: byte-exact ports of src/state/canonical.py -----------

/// Unsigned LEB128, appended to `out`. Matches `canonical.encode_uvarint`.
pub fn encode_uvarint(mut value: u64, out: &mut Vec<u8>) {
    loop {
        let byte = (value & 0x7f) as u8;
        value >>= 7;
        if value != 0 {
            out.push(byte | 0x80);
        } else {
            out.push(byte);
            break;
        }
    }
}

/// `b"zenodex:" + label + b":v" + decimal(version) + b"\x00"`.
/// Matches `canonical.domain_sep_bytes` (ASCII-only, NUL-terminated).
pub fn domain_sep_bytes(label: &str, version: u32) -> Vec<u8> {
    let mut out = Vec::new();
    out.extend_from_slice(b"zenodex:");
    out.extend_from_slice(label.as_bytes());
    out.extend_from_slice(b":v");
    out.extend_from_slice(format!("{}", version).as_bytes());
    out.push(0x00);
    out
}

fn hex_val(c: u8) -> Result<u8, &'static str> {
    match c {
        b'0'..=b'9' => Ok(c - b'0'),
        b'a'..=b'f' => Ok(c - b'a' + 10),
        b'A'..=b'F' => Ok(c - b'A' + 10),
        _ => Err("invalid hex character"),
    }
}

/// `0x`-prefixed fixed-width hex -> bytes. Matches `canonical.hex_to_bytes_fixed`
/// (rejects wrong length / non-hex; fail-closed, no panic).
pub fn hex_to_bytes_fixed(hex_str: &str, nbytes: usize) -> Result<Vec<u8>, &'static str> {
    if !hex_str.starts_with("0x") || hex_str.len() != 2 + 2 * nbytes {
        return Err("hex must be 0x-prefixed and exactly nbytes wide");
    }
    let body = hex_str.as_bytes();
    let mut out = Vec::with_capacity(nbytes);
    let mut i = 2usize;
    while i < body.len() {
        out.push((hex_val(body[i])? << 4) | hex_val(body[i + 1])?);
        i += 2;
    }
    Ok(out)
}

// --- canonical CLOB book ------------------------------------------------------

const ASSET_NBYTES: usize = 32;
const ORDER_ID_NBYTES: usize = 32;
const OWNER_NBYTES: usize = 48;
const BOOK_DOMAIN_SEP_LABEL: &str = "clob_book";
const BOOK_VERSION: u32 = 1;

#[derive(Clone, Debug)]
pub struct ClobOrderV1 {
    pub side_code: u8, // 0 = BUY, 1 = SELL
    pub price_q_per_base: u64,
    pub base_qty: u64,
    pub sequence: u64,
    pub order_id: String, // 0x + 64 hex (32 bytes), canonical lowercase
    pub owner: String,    // 0x + 96 hex (48 bytes), canonical lowercase
}

/// Strict total-order matching/canonical key, mirroring
/// `clob_book.order_priority_key`. BUY uses `-price` (highest first); SELL uses
/// `+price` (lowest first); then sequence, then order_id lexicographic.
fn priority_key(o: &ClobOrderV1) -> (u8, i128, u64, &str) {
    let price_term = if o.side_code == 0 {
        -(o.price_q_per_base as i128)
    } else {
        o.price_q_per_base as i128
    };
    (o.side_code, price_term, o.sequence, o.order_id.as_str())
}

#[derive(Clone, Debug)]
pub struct ClobBookV1 {
    pub base_asset: String,
    pub quote_asset: String,
    pub orders: Vec<ClobOrderV1>, // canonical (order_priority_key) order
}

impl ClobBookV1 {
    /// Canonicalize into strict `order_priority_key` order (mirrors
    /// `ClobBook.__post_init__`), so the root is insertion-order independent.
    pub fn new(base_asset: String, quote_asset: String, mut orders: Vec<ClobOrderV1>) -> Self {
        orders.sort_by(|a, b| priority_key(a).cmp(&priority_key(b)));
        Self { base_asset, quote_asset, orders }
    }

    /// Domain-separated SHA-256 commitment to the resting book -- byte-for-byte
    /// identical to `ClobBook.state_root`.
    pub fn state_root(&self) -> Result<[u8; 32], &'static str> {
        let mut payload = domain_sep_bytes(BOOK_DOMAIN_SEP_LABEL, BOOK_VERSION);
        payload.extend_from_slice(&hex_to_bytes_fixed(&self.base_asset, ASSET_NBYTES)?);
        payload.extend_from_slice(&hex_to_bytes_fixed(&self.quote_asset, ASSET_NBYTES)?);
        encode_uvarint(self.orders.len() as u64, &mut payload);
        for o in &self.orders {
            encode_uvarint(o.side_code as u64, &mut payload);
            encode_uvarint(o.price_q_per_base, &mut payload);
            encode_uvarint(o.base_qty, &mut payload);
            encode_uvarint(o.sequence, &mut payload);
            payload.extend_from_slice(&hex_to_bytes_fixed(&o.order_id, ORDER_ID_NBYTES)?);
            payload.extend_from_slice(&hex_to_bytes_fixed(&o.owner, OWNER_NBYTES)?);
        }
        let mut hasher = Sha256::new();
        hasher.update(&payload);
        Ok(hasher.finalize().into())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::string::ToString;
    use alloc::vec;

    fn hexstr(bytes: &[u8]) -> String {
        let mut s = String::with_capacity(bytes.len() * 2);
        for b in bytes {
            s.push_str(&format!("{:02x}", b));
        }
        s
    }

    #[test]
    fn uvarint_known_vectors() {
        let mut out = Vec::new();
        encode_uvarint(0, &mut out);
        assert_eq!(out, vec![0x00]);
        out.clear();
        encode_uvarint(127, &mut out);
        assert_eq!(out, vec![0x7f]);
        out.clear();
        encode_uvarint(128, &mut out);
        assert_eq!(out, vec![0x80, 0x01]);
        out.clear();
        encode_uvarint(300, &mut out);
        assert_eq!(out, vec![0xac, 0x02]);
    }

    #[test]
    fn domain_sep_matches_python_format() {
        assert_eq!(domain_sep_bytes("clob_book", 1), b"zenodex:clob_book:v1\x00".to_vec());
    }

    #[test]
    fn clob_book_root_single_buy_matches_python_fixture() {
        // In-crate smoke: the single_buy fixture case (the no_std shared crate has
        // no JSON parser; the FULL cross-language corpus parity lives in the CLI
        // crate's tests/clob_book_root_parity.rs, which has serde_json). If this
        // hardcoded hex drifts, regenerate via tools/gen_clob_book_root_fixture.py.
        let book = ClobBookV1::new(
            "0x".to_string() + &"11".repeat(ASSET_NBYTES),
            "0x".to_string() + &"22".repeat(ASSET_NBYTES),
            vec![ClobOrderV1 {
                side_code: 0, // BUY
                price_q_per_base: 100,
                base_qty: 5,
                sequence: 1,
                order_id: format!("0x{:064x}", 1u64),
                owner: "0x".to_string() + &"aa".repeat(OWNER_NBYTES),
            }],
        );
        assert_eq!(
            hexstr(&book.state_root().unwrap()),
            "6e13539ee5e3de14f9a3c92f0bee97f85434eacce426b229b371e68bc66463ce",
        );
    }
}
