FROM python:3.11-slim-trixie@sha256:a3ab0b966bc4e91546a033e22093cb840908979487a9fc0e6e38295747e49ac0

RUN apt-get update -o Acquire::Retries=3 \
  && apt-get install -y --no-install-recommends gcc g++ make libgmp-dev \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /work
