FROM python:3.11-slim-trixie

RUN apt-get update -o Acquire::Retries=3 \
  && apt-get install -y --no-install-recommends gcc-14 g++-14 make libgmp-dev cmake \
  && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 140 \
  && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 140 \
  && update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-14 140 \
  && update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-14 140 \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /work
