import Mathlib.Data.Set.Basic

/-!
# Forward Simulation Disaster Lifting

This file proves a reusable disaster-state proof pattern:

* concrete traces lift to abstract traces by forward simulation,
* abstract invariant preservation transfers to concrete safety,
* if the abstract invariant excludes a concrete disaster through the simulation
  relation, then that disaster is unreachable,
* deterministic abstraction and set-concretization variants are instances of
  the same theorem,
* synchronous and asynchronous product simulations compose.

The statements are intentionally small.  Domain-specific systems can instantiate
`LTS`, `ForwardSim`, and the disaster predicate without changing the core proof.
-/

namespace TauSwap
namespace DisasterSimulation

universe u v w u₁ u₂ v₁ v₂

/-- A labelled transition system. -/
structure LTS (State : Type u) (Act : Type v) where
  step : State -> Act -> State -> Prop

/-- Reflexive transitive reachability generated by labelled steps. -/
inductive Reachable {State : Type u} {Act : Type v} (T : LTS State Act) :
    State -> State -> Prop where
  | refl (s : State) : Reachable T s s
  | tail {s t u : State} {act : Act} :
      Reachable T s t -> T.step t act u -> Reachable T s u

/-- An invariant is preserved by every transition. -/
def Preserved {State : Type u} {Act : Type v}
    (T : LTS State Act) (Inv : State -> Prop) : Prop :=
  ∀ {s s' : State} {act : Act}, Inv s -> T.step s act s' -> Inv s'

/-- A forward simulation from concrete states to abstract states. -/
def ForwardSim
    {CState : Type u} {AState : Type v} {Act : Type w}
    (C : LTS CState Act) (A : LTS AState Act)
    (R : CState -> AState -> Prop) : Prop :=
  ∀ {c c' : CState} {a : AState} {act : Act},
    R c a -> C.step c act c' -> ∃ a', A.step a act a' ∧ R c' a'

/-- Preserved invariants hold at every reachable state. -/
theorem invariant_of_reachable
    {State : Type u} {Act : Type v}
    {T : LTS State Act} {Inv : State -> Prop}
    (hpres : Preserved T Inv)
    {s₀ sN : State}
    (hreach : Reachable T s₀ sN)
    (hinit : Inv s₀) :
    Inv sN := by
  induction hreach with
  | refl =>
      exact hinit
  | tail hprefix hstep ih =>
      exact hpres ih hstep

/-- Forward simulation lifts every concrete trace to a matching abstract trace. -/
theorem forward_sim_reachable
    {CState : Type u} {AState : Type v} {Act : Type w}
    {C : LTS CState Act} {A : LTS AState Act}
    {R : CState -> AState -> Prop}
    (hsim : ForwardSim C A R)
    {c₀ cN : CState} {a₀ : AState}
    (hinit : R c₀ a₀)
    (hreach : Reachable C c₀ cN) :
    ∃ aN, Reachable A a₀ aN ∧ R cN aN := by
  induction hreach with
  | refl =>
      exact ⟨a₀, Reachable.refl a₀, hinit⟩
  | tail hprefix hstep ih =>
      rcases ih with ⟨aMid, habsPrefix, hrelMid⟩
      rcases hsim hrelMid hstep with ⟨aNext, habsStep, hrelNext⟩
      exact ⟨aNext, Reachable.tail habsPrefix habsStep, hrelNext⟩

/-- Abstract invariant preservation transfers to concrete safety. -/
theorem concrete_safe_of_abstract_invariant
    {CState : Type u} {AState : Type v} {Act : Type w}
    {C : LTS CState Act} {A : LTS AState Act}
    {R : CState -> AState -> Prop}
    {Inv : AState -> Prop} {Safe : CState -> Prop}
    (hsim : ForwardSim C A R)
    (hpres : Preserved A Inv)
    (htransfer : ∀ {c a}, R c a -> Inv a -> Safe c)
    {c₀ cN : CState} {a₀ : AState}
    (hinitR : R c₀ a₀)
    (hinitInv : Inv a₀)
    (hreach : Reachable C c₀ cN) :
    Safe cN := by
  rcases forward_sim_reachable hsim hinitR hreach with ⟨aN, habsReach, hrelN⟩
  exact htransfer hrelN (invariant_of_reachable hpres habsReach hinitInv)

/-- If the abstract invariant excludes a concrete disaster through the
simulation relation, then no reachable concrete state satisfies that disaster
predicate. -/
theorem no_concrete_disaster_of_abstract_simulation
    {CState : Type u} {AState : Type v} {Act : Type w}
    {C : LTS CState Act} {A : LTS AState Act}
    {R : CState -> AState -> Prop}
    {Inv : AState -> Prop} {Disaster : CState -> Prop}
    (hsim : ForwardSim C A R)
    (hpres : Preserved A Inv)
    (hexclude : ∀ {c a}, R c a -> Inv a -> ¬ Disaster c)
    {c₀ cN : CState} {a₀ : AState}
    (hinitR : R c₀ a₀)
    (hinitInv : Inv a₀)
    (hreach : Reachable C c₀ cN) :
    ¬ Disaster cN := by
  rcases forward_sim_reachable hsim hinitR hreach with ⟨aN, habsReach, hrelN⟩
  exact hexclude hrelN (invariant_of_reachable hpres habsReach hinitInv)

/-- Graph relation induced by a deterministic abstraction function. -/
def GraphRel {CState : Type u} {AState : Type v}
    (abs : CState -> AState) : CState -> AState -> Prop :=
  fun c a => abs c = a

/-- A deterministic abstraction is step-compatible when every concrete step maps
to an abstract step. -/
def DeterministicAbstraction
    {CState : Type u} {AState : Type v} {Act : Type w}
    (C : LTS CState Act) (A : LTS AState Act)
    (abs : CState -> AState) : Prop :=
  ∀ {c c' : CState} {act : Act}, C.step c act c' -> A.step (abs c) act (abs c')

/-- Deterministic abstractions are forward simulations via their graph relation. -/
theorem deterministicAbstraction_forwardSim
    {CState : Type u} {AState : Type v} {Act : Type w}
    {C : LTS CState Act} {A : LTS AState Act}
    {abs : CState -> AState}
    (habs : DeterministicAbstraction C A abs) :
    ForwardSim C A (GraphRel abs) := by
  intro c c' a act hrel hstep
  subst a
  exact ⟨abs c', habs hstep, rfl⟩

/-- Disaster exclusion specialized to deterministic abstraction functions. -/
theorem no_concrete_disaster_of_deterministic_abstraction
    {CState : Type u} {AState : Type v} {Act : Type w}
    {C : LTS CState Act} {A : LTS AState Act}
    {abs : CState -> AState}
    {Inv : AState -> Prop} {Disaster : CState -> Prop}
    (habs : DeterministicAbstraction C A abs)
    (hpres : Preserved A Inv)
    (hexclude : ∀ c, Inv (abs c) -> ¬ Disaster c)
    {c₀ cN : CState}
    (hinitInv : Inv (abs c₀))
    (hreach : Reachable C c₀ cN) :
    ¬ Disaster cN := by
  apply no_concrete_disaster_of_abstract_simulation
    (hsim := deterministicAbstraction_forwardSim habs)
    (hpres := hpres)
    (hexclude := ?_)
    (hinitR := rfl)
    (hinitInv := hinitInv)
    (hreach := hreach)
  intro c a hrel hinv
  subst a
  exact hexclude c hinv

/-- Set-concretization relation.  A concrete state is related to an abstract
state when it is a member of that abstract state's concretization set. -/
def Concretizes {CState : Type u} {AState : Type v}
    (gamma : AState -> Set CState) : CState -> AState -> Prop :=
  fun c a => c ∈ gamma a

/-- A set-valued concretization is step-compatible when every concrete step from
an abstract state's concretization lands in some successor concretization. -/
def SetConcretizationSim
    {CState : Type u} {AState : Type v} {Act : Type w}
    (C : LTS CState Act) (A : LTS AState Act)
    (gamma : AState -> Set CState) : Prop :=
  ∀ {c c' : CState} {a : AState} {act : Act},
    c ∈ gamma a -> C.step c act c' -> ∃ a', A.step a act a' ∧ c' ∈ gamma a'

/-- Set-valued concretizations are forward simulations. -/
theorem setConcretization_forwardSim
    {CState : Type u} {AState : Type v} {Act : Type w}
    {C : LTS CState Act} {A : LTS AState Act}
    {gamma : AState -> Set CState}
    (hgamma : SetConcretizationSim C A gamma) :
    ForwardSim C A (Concretizes gamma) := by
  intro c c' a act hrel hstep
  exact hgamma hrel hstep

/-- Disaster exclusion specialized to set-valued concretization. -/
theorem no_concrete_disaster_of_set_concretization
    {CState : Type u} {AState : Type v} {Act : Type w}
    {C : LTS CState Act} {A : LTS AState Act}
    {gamma : AState -> Set CState}
    {Inv : AState -> Prop} {Disaster : CState -> Prop}
    (hgamma : SetConcretizationSim C A gamma)
    (hpres : Preserved A Inv)
    (hexclude : ∀ {c a}, c ∈ gamma a -> Inv a -> ¬ Disaster c)
    {c₀ cN : CState} {a₀ : AState}
    (hinitR : c₀ ∈ gamma a₀)
    (hinitInv : Inv a₀)
    (hreach : Reachable C c₀ cN) :
    ¬ Disaster cN :=
  no_concrete_disaster_of_abstract_simulation
    (hsim := setConcretization_forwardSim hgamma)
    (hpres := hpres)
    (hexclude := hexclude)
    (hinitR := hinitR)
    (hinitInv := hinitInv)
    (hreach := hreach)

/-- Product relation for two component simulations. -/
def ProdRel
    {C₁ : Type u₁} {A₁ : Type v₁} {C₂ : Type u₂} {A₂ : Type v₂}
    (R₁ : C₁ -> A₁ -> Prop) (R₂ : C₂ -> A₂ -> Prop) :
    C₁ × C₂ -> A₁ × A₂ -> Prop :=
  fun c a => R₁ c.1 a.1 ∧ R₂ c.2 a.2

/-- Synchronous product: both components step under the same action. -/
def syncProduct
    {S₁ : Type u₁} {S₂ : Type u₂} {Act : Type w}
    (T₁ : LTS S₁ Act) (T₂ : LTS S₂ Act) : LTS (S₁ × S₂) Act where
  step s act s' := T₁.step s.1 act s'.1 ∧ T₂.step s.2 act s'.2

/-- Asynchronous product: one component steps while the other stutters. -/
def asyncProduct
    {S₁ : Type u₁} {S₂ : Type u₂} {Act₁ : Type v₁} {Act₂ : Type v₂}
    (T₁ : LTS S₁ Act₁) (T₂ : LTS S₂ Act₂) :
    LTS (S₁ × S₂) (Sum Act₁ Act₂) where
  step s act s' :=
    match act with
    | Sum.inl act₁ => T₁.step s.1 act₁ s'.1 ∧ s'.2 = s.2
    | Sum.inr act₂ => s'.1 = s.1 ∧ T₂.step s.2 act₂ s'.2

/-- Forward simulations compose through synchronous products. -/
theorem syncProduct_forwardSim
    {C₁ : Type u₁} {A₁ : Type v₁} {C₂ : Type u₂} {A₂ : Type v₂}
    {Act : Type w}
    {Csys₁ : LTS C₁ Act} {Asys₁ : LTS A₁ Act}
    {Csys₂ : LTS C₂ Act} {Asys₂ : LTS A₂ Act}
    {R₁ : C₁ -> A₁ -> Prop} {R₂ : C₂ -> A₂ -> Prop}
    (hsim₁ : ForwardSim Csys₁ Asys₁ R₁)
    (hsim₂ : ForwardSim Csys₂ Asys₂ R₂) :
    ForwardSim
      (syncProduct Csys₁ Csys₂)
      (syncProduct Asys₁ Asys₂)
      (ProdRel R₁ R₂) := by
  intro c c' a act hrel hstep
  rcases c with ⟨c₁, c₂⟩
  rcases c' with ⟨c₁', c₂'⟩
  rcases a with ⟨a₁, a₂⟩
  rcases hrel with ⟨hrel₁, hrel₂⟩
  rcases hstep with ⟨hstep₁, hstep₂⟩
  rcases hsim₁ hrel₁ hstep₁ with ⟨a₁', habs₁, hrel₁'⟩
  rcases hsim₂ hrel₂ hstep₂ with ⟨a₂', habs₂, hrel₂'⟩
  exact ⟨(a₁', a₂'), ⟨habs₁, habs₂⟩, ⟨hrel₁', hrel₂'⟩⟩

/-- Forward simulations compose through asynchronous products. -/
theorem asyncProduct_forwardSim
    {C₁ : Type u₁} {A₁ : Type v₁} {C₂ : Type u₂} {A₂ : Type v₂}
    {Act₁ : Type w} {Act₂ : Type v}
    {Csys₁ : LTS C₁ Act₁} {Asys₁ : LTS A₁ Act₁}
    {Csys₂ : LTS C₂ Act₂} {Asys₂ : LTS A₂ Act₂}
    {R₁ : C₁ -> A₁ -> Prop} {R₂ : C₂ -> A₂ -> Prop}
    (hsim₁ : ForwardSim Csys₁ Asys₁ R₁)
    (hsim₂ : ForwardSim Csys₂ Asys₂ R₂) :
    ForwardSim
      (asyncProduct Csys₁ Csys₂)
      (asyncProduct Asys₁ Asys₂)
      (ProdRel R₁ R₂) := by
  intro c c' a act hrel hstep
  rcases c with ⟨c₁, c₂⟩
  rcases c' with ⟨c₁', c₂'⟩
  rcases a with ⟨a₁, a₂⟩
  rcases hrel with ⟨hrel₁, hrel₂⟩
  cases act with
  | inl act₁ =>
      rcases hstep with ⟨hstep₁, hstay₂⟩
      rcases hsim₁ hrel₁ hstep₁ with ⟨a₁', habs₁, hrel₁'⟩
      have hrel₂' : R₂ c₂' a₂ := by
        cases hstay₂
        exact hrel₂
      exact ⟨(a₁', a₂), ⟨habs₁, rfl⟩, ⟨hrel₁', hrel₂'⟩⟩
  | inr act₂ =>
      rcases hstep with ⟨hstay₁, hstep₂⟩
      rcases hsim₂ hrel₂ hstep₂ with ⟨a₂', habs₂, hrel₂'⟩
      have hrel₁' : R₁ c₁' a₁ := by
        cases hstay₁
        exact hrel₁
      exact ⟨(a₁, a₂'), ⟨rfl, habs₂⟩, ⟨hrel₁', hrel₂'⟩⟩

end DisasterSimulation
end TauSwap
