"""Per-curve revenue tracking for curve selection prediction market.

Tracks LP revenue generated by each of the 5 AMM curve families
(CPMM, cubic_sum, sum_boost, quartic_blend, quintic_blend) to
determine which curve produces the best LP returns.

Revenue is measured as total fees collected per curve over an epoch.
"""

from __future__ import annotations

from dataclasses import dataclass, replace


NUM_CURVES = 5

CURVE_NAMES = ("cpmm", "cubic_sum", "sum_boost", "quartic_blend", "quintic_blend")


@dataclass(frozen=True)
class CurveRevenueState:
    """Revenue accumulated per curve over current prediction epoch."""

    # Revenue counters (fee units collected per curve)
    revenue_cpmm: int = 0
    revenue_cubic_sum: int = 0
    revenue_sum_boost: int = 0
    revenue_quartic_blend: int = 0
    revenue_quintic_blend: int = 0

    # Epoch tracking
    epoch: int = 0
    epoch_start_revenue_cpmm: int = 0
    epoch_start_revenue_cubic_sum: int = 0
    epoch_start_revenue_sum_boost: int = 0
    epoch_start_revenue_quartic_blend: int = 0
    epoch_start_revenue_quintic_blend: int = 0

    def __post_init__(self) -> None:
        for name in (
            "revenue_cpmm", "revenue_cubic_sum", "revenue_sum_boost",
            "revenue_quartic_blend", "revenue_quintic_blend",
            "epoch_start_revenue_cpmm", "epoch_start_revenue_cubic_sum",
            "epoch_start_revenue_sum_boost", "epoch_start_revenue_quartic_blend",
            "epoch_start_revenue_quintic_blend",
        ):
            val = getattr(self, name)
            if not isinstance(val, int) or isinstance(val, bool):
                raise TypeError(f"{name} must be an int")
            if val < 0:
                raise ValueError(f"{name} must be non-negative: {val}")

    def get_revenue(self, curve_id: int) -> int:
        """Get cumulative revenue for curve_id (0-4)."""
        return (
            self.revenue_cpmm,
            self.revenue_cubic_sum,
            self.revenue_sum_boost,
            self.revenue_quartic_blend,
            self.revenue_quintic_blend,
        )[curve_id]

    def get_epoch_revenue(self, curve_id: int) -> int:
        """Get revenue earned during current epoch for curve_id."""
        starts = (
            self.epoch_start_revenue_cpmm,
            self.epoch_start_revenue_cubic_sum,
            self.epoch_start_revenue_sum_boost,
            self.epoch_start_revenue_quartic_blend,
            self.epoch_start_revenue_quintic_blend,
        )
        return self.get_revenue(curve_id) - starts[curve_id]

    def get_winner(self) -> int:
        """Return curve_id with highest epoch revenue. Tie-break: lowest id."""
        best_id = 0
        best_rev = self.get_epoch_revenue(0)
        for cid in range(1, NUM_CURVES):
            rev = self.get_epoch_revenue(cid)
            if rev > best_rev:
                best_id = cid
                best_rev = rev
        return best_id

    def roll_epoch(self) -> CurveRevenueState:
        """Advance epoch: snapshot current revenues as epoch_start, increment epoch."""
        return replace(
            self,
            epoch=self.epoch + 1,
            epoch_start_revenue_cpmm=self.revenue_cpmm,
            epoch_start_revenue_cubic_sum=self.revenue_cubic_sum,
            epoch_start_revenue_sum_boost=self.revenue_sum_boost,
            epoch_start_revenue_quartic_blend=self.revenue_quartic_blend,
            epoch_start_revenue_quintic_blend=self.revenue_quintic_blend,
        )

    def add_revenue(self, curve_id: int, amount: int) -> CurveRevenueState:
        """Add revenue to a specific curve. Amount must be non-negative."""
        if amount < 0:
            raise ValueError(f"amount must be non-negative: {amount}")
        if not (0 <= curve_id < NUM_CURVES):
            raise ValueError(f"curve_id must be in [0, {NUM_CURVES}): {curve_id}")
        fields = {
            0: "revenue_cpmm",
            1: "revenue_cubic_sum",
            2: "revenue_sum_boost",
            3: "revenue_quartic_blend",
            4: "revenue_quintic_blend",
        }
        field = fields[curve_id]
        return replace(self, **{field: getattr(self, field) + amount})
