"""Closed Python type admission for GlobalSettlementABI V1 canonical bytes.

This module is intentionally data-only.  It imports no domain types, performs
no discovery, and exposes no registration API.  The canonical encoder resolves
these names only against class objects already loaded by their defining
modules, then requires exact identity before invoking a class-owned serializer.
"""

from __future__ import annotations

from typing import Final

GLOBAL_SETTLEMENT_CANONICAL_SERIALIZER_TYPES_V1: Final[tuple[str, ...]] = (
    "src.core.asset_lane_projection_v1.AssetLaneCoordinatorContextV1",
    "src.core.asset_lane_projection_v1.AssetLaneModuleCompatibilityV1",
    "src.core.asset_lane_projection_v1.AssetLanePrivatePortV1",
    "src.core.asset_lane_projection_v1.AssetLaneStateProjectionV1",
    "src.core.asset_origin_registration_transition_v1.AssetOriginRecordV1",
    "src.core.asset_origin_registration_transition_v1.AssetOriginRegistrationPolicyV1",
    "src.core.asset_transfer_types_v1.AssetTransferCommandV1",
    "src.core.asset_transfer_types_v1.AssetTransferContextV1",
    "src.core.asset_transfer_types_v1.AssetTransferPolicyV1",
    "src.core.asset_transfer_types_v1.AssetTransferStateV1",
    "src.core.economic_command_authentication_types_v1.EconomicCommandIntentV1",
    "src.core.economic_command_authorization_registry_v1.EconomicCommandAuthorizationV1",
    "src.core.economic_command_signature_verifier_deployment_v1.CommandSignatureVerifierEvidenceArtifactV1",
    "src.core.economic_command_signature_verifier_registry_v1.EconomicCommandSignatureVerifierReleaseV1",
    "src.core.economic_initial_state_atom_coverage_v1.EconomicInitialStateAtomOccurrenceV1",
    "src.core.economic_initial_state_atom_coverage_v1.EconomicInitialStateAtomSourceV1",
    "src.core.economic_initial_state_atom_coverage_v1.EconomicInitialStateSourceManifestV1",
    "src.core.economic_initial_state_v1.EconomicInitialStateCertificateV1",
    "src.core.economic_receipt_verifier_evidence_v1.EconomicReceiptVerifierEvidenceArtifactV1",
    "src.core.economic_receipt_verifier_registry_v1.EconomicReceiptVerifierReleaseV1",
    "src.core.global_economic_durable_activation_v1.DurableEconomicActivationRecordV1",
    "src.core.global_economic_durable_activation_v1.DurableEconomicComponentCommitmentV1",
    "src.core.global_economic_proof_v1.CommandAggregationJournalV1",
    "src.core.global_economic_proof_v1.EconomicCommandOccurrenceV1",
    "src.core.global_economic_proof_v1.GlobalEconomicEpochCertificateV1",
    "src.core.global_economic_proof_v1.LaneCompositionJournalV1",
    "src.core.global_economic_proof_v1.LaneModuleTransitionJournalV1",
    "src.core.global_economic_proof_v1.MigrationObjectRowV1",
    "src.core.global_economic_proof_v1.RouteCompositionJournalV1",
    "src.core.global_economic_proof_v1.StateMigrationCertificateV1",
    "src.core.global_economic_state_delta_v1._AmountDeltaRowV1",
    "src.core.global_economic_state_delta_v1._SupplyDeltaRowV1",
    "src.core.global_settlement_types_v1.AssetConservationRowV1",
    "src.core.global_settlement_types_v1.AssetSupplyV1",
    "src.core.global_settlement_types_v1.EconomicAmountV1",
    "src.core.global_settlement_types_v1.EconomicEffectRowV1",
    "src.core.global_settlement_types_v1.EconomicPolicyBindingV1",
    "src.core.global_settlement_types_v1.EconomicPolicyRegistryV1",
    "src.core.global_settlement_types_v1.EconomicProfileSnapshotV1",
    "src.core.global_settlement_types_v1.ExternalOutboxEnqueueV1",
    "src.core.global_settlement_types_v1.FeeConservationRowV1",
    "src.core.global_settlement_types_v1.GlobalEconomicEffectPlanV1",
    "src.core.global_settlement_types_v1.GlobalEconomicStateV1",
    "src.core.global_settlement_types_v1.LaneCoordinatorRegistryV1",
    "src.core.global_settlement_types_v1.LaneCoordinatorReleaseV1",
    "src.core.global_settlement_types_v1.LaneModuleReleaseV1",
    "src.core.global_settlement_types_v1.LaneRegistryV1",
    "src.core.global_settlement_types_v1.LaneStateRootV1",
    "src.core.global_settlement_types_v1.LaneWriteV1",
    "src.core.global_settlement_types_v1.OracleOccurrenceStateV1",
    "src.core.global_settlement_types_v1.OutboxStateV1",
    "src.core.global_settlement_types_v1.ReplayStateV1",
    "src.core.global_settlement_types_v1.RouteRegistryV1",
    "src.core.global_settlement_types_v1.RouteReleaseV1",
    "src.core.global_settlement_types_v1.TerminalObligationV1",
    "src.core.lane_capability_registry_v1.LaneCapabilitySetV1",
    "src.core.managed_asset_lifecycle_types_v1.ManagedAssetLifecycleCommandV1",
    "src.core.managed_asset_lifecycle_types_v1.ManagedAssetLifecycleContextV1",
    "src.core.managed_asset_lifecycle_types_v1.ManagedAssetLifecyclePolicyV1",
    "src.core.managed_asset_lifecycle_types_v1.ManagedAssetLifecycleStateV1",
    "src.core.perps_margin_types_v1.PerpsMarginAccountV1",
    "src.core.perps_margin_types_v1.PerpsMarginCommandV1",
    "src.core.perps_margin_types_v1.PerpsMarginContextV1",
    "src.core.perps_margin_types_v1.PerpsMarginStateV1",
    "src.core.route_global_state_projection_v1.RouteGlobalLaneProjectionV1",
    "src.core.zdex_atomic_buyback_lane_receipt_v2._ZDEXBuybackLaneCoordinatorStatementV2",
    "src.core.zdex_atomic_buyback_route_receipt_v2._ZDEXAtomicBuybackRouteStatementV2",
    "src.core.zdex_buyback_price_safety_v1.ZDEXBuybackOraclePriceOccurrenceV1",
    "src.core.zdex_buyback_spend_v1.ZDEXBuybackSpendStateV1",
    "src.core.zdex_buyback_spot_safety_receipt_v1.ZDEXBuybackSpotSafetyPurchaseJournalV2",
    "src.core.zdex_fee_allocation_types_v1.ZDEXFeeAllocationOccurrenceV1",
    "src.core.zdex_fee_allocation_types_v1.ZDEXFeeDestinationAmountV1",
    "src.core.zdex_fee_allocation_types_v1.ZDEXFeeShareV1",
    "src.core.zdex_fee_allocation_types_v1.ZDEXFeeStateV1",
    "src.core.zdex_hyperdeflation_types_v1.ZDEXAmountBucketV1",
    "src.core.zdex_hyperdeflation_types_v1.ZDEXSupplyStateV1",
    "src.core.zdex_purchase_burn_route_types_v1.ZDEXAMMPurchaseJournalV1",
    "src.core.zdex_purchase_burn_route_types_v1.ZDEXAMMPurchaseJournalV2",
    "src.core.zdex_purchase_burn_route_types_v1.ZDEXBurnJournalV1",
    "src.core.zdex_spot_buyback_transition_v1.ZDEXSpotFlowIdentityV1",
    "src.core.zdex_spot_buyback_transition_v1.ZDEXSpotOracleOccurrenceV1",
    "src.core.zdex_spot_buyback_transition_v1.ZDEXSpotPoolCreationReleaseV1",
    "src.core.zdex_spot_buyback_transition_v1.ZDEXSpotPoolDefinitionV1",
    "src.core.zdex_spot_buyback_transition_v1.ZDEXSpotPoolV1",
    "src.core.zdex_spot_buyback_transition_v1.ZDEXSpotRegisteredCurveReleaseV1",
    "src.core.zdex_spot_buyback_transition_v2.ZDEXSpotBuybackJournalV2",
    "src.core.zdex_tokenomics_buyback_transition_v1.ZDEXTokenomicsSupplyControlStateV1",
    "src.core.zdex_tokenomics_buyback_transition_v2.ZDEXTokenomicsBuybackJournalV2",
    "src.core.zdex_tokenomics_lane_v1.ZDEXTokenomicsLaneStateV1",
    "src.integration.global_economic_commit_v1.EconomicEpochBodyAndStateV1",
    "src.integration.global_economic_commit_v1.PublishedEconomicEpochV1",
    "src.integration.global_economic_durable_epoch_v1.DurableEconomicEpochRecordV1",
)

GLOBAL_SETTLEMENT_CANONICAL_ENUM_TYPES_V1: Final[tuple[str, ...]] = (
    "src.core.asset_origin_registration_transition_v1.AssetOriginKindV1",
    "src.core.economic_command_signature_verifier_registry_v1.CommandSignatureVerifierEvidenceStatusV1",
    "src.core.economic_initial_state_atom_coverage_v1.EconomicInitialStateAtomClassificationV1",
    "src.core.economic_initial_state_atom_coverage_v1.EconomicInitialStateAtomKindV1",
    "src.core.economic_initial_state_atom_coverage_v1.EconomicInitialStateKindV1",
    "src.core.economic_receipt_verifier_registry_v1.EconomicReceiptVerifierEvidenceStatusV1",
    "src.core.economic_receipt_verifier_registry_v1.EconomicReceiptVerifierSelectionPurposeV1",
    "src.core.external_custody_disabled_lane_v1.ExternalCustodyCommandKindV1",
    "src.core.global_economic_authority_head_v1.GlobalEconomicAuthorityStatusV1",
    "src.core.global_economic_durable_activation_v1.DurableEconomicComponentKindV1",
    "src.core.global_economic_proof_v1.MigrationObjectClassV1",
    "src.core.global_economic_proof_v1.ReceiptKindV1",
    "src.core.global_settlement_types_v1.EconomicEffectKindV1",
    "src.core.global_settlement_types_v1.EvidenceStatusV1",
    "src.core.global_settlement_types_v1.LaneIdV1",
    "src.core.global_settlement_types_v1.OutboxStatusV1",
    "src.core.global_settlement_types_v1.ProfileStatusV1",
    "src.core.global_settlement_types_v1.ReleaseStatusV1",
    "src.core.global_settlement_types_v1.TerminalObligationStatusV1",
    "src.core.lane_capability_registry_v1.LaneCapabilityDispositionV1",
    "src.core.managed_asset_lifecycle_types_v1.ManagedAssetClassV1",
    "src.core.perps_margin_types_v1.PerpsMarginAccountStatusV1",
    "src.core.perps_margin_types_v1.PerpsMarginMarketStatusV1",
    "src.core.proof_rewards_policy_blocked_lane_v1.ProofRewardsCapabilityV1",
    "src.core.receipt_backed_asset_lane_composition_v1.LaneCompositionAuthorityLevelV1",
    "src.core.zdex_fee_allocation_types_v1.ZDEXFeeDestinationV1",
    "src.core.zdex_spot_buyback_transition_v1.ZDEXSpotCurveKindV1",
    "src.core.zdex_spot_buyback_transition_v1.ZDEXSpotFlowRoleV1",
    "src.core.zdex_spot_buyback_transition_v1.ZDEXSpotOracleStatusV1",
    "src.core.zdex_spot_buyback_transition_v1.ZDEXSpotPoolStatusV1",
)

GLOBAL_SETTLEMENT_CANONICAL_SERIALIZER_TYPE_SET_V1: Final[frozenset[str]] = frozenset(
    GLOBAL_SETTLEMENT_CANONICAL_SERIALIZER_TYPES_V1
)
GLOBAL_SETTLEMENT_CANONICAL_ENUM_TYPE_SET_V1: Final[frozenset[str]] = frozenset(
    GLOBAL_SETTLEMENT_CANONICAL_ENUM_TYPES_V1
)
