"""
Autonomous agent interfaces for TauSwap DEX
"""

from importlib import import_module
from typing import Any

from .intent_signer import (
    create_swap_intent,
    sign_intent,
    verify_intent_signature,
)
from .relayer import (
    batch_intents,
    create_batch,
)
from .strategy_ir import (
    NotionalCaps,
    PolicyBackend,
    RiskLimits,
    StrategyAction,
    StrategyControls,
    StrategyIR,
    StrategyTemplate,
    StrategyWindow,
)

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "AUTOTRADER_KRR_DEFAULT_BACKEND": (".krr_policy_advisor", "AUTOTRADER_KRR_DEFAULT_BACKEND"),
    "AUTOTRADER_KRR_SCHEMA": (".krr_policy_advisor", "AUTOTRADER_KRR_SCHEMA"),
    "advise_autotrader_krr": (".krr_policy_advisor", "advise_autotrader_krr"),
    "autotrader_krr_check_options": (".krr_policy_advisor", "autotrader_krr_check_options"),
    "autotrader_krr_semantic_signature": (".krr_policy_advisor", "autotrader_krr_semantic_signature"),
    "build_autotrader_krr_history": (".krr_policy_history", "build_autotrader_krr_history"),
    "AUTOTRADER_CLIENT_POLICY_SURFACE_SCHEMA": (".autotrader_client_policy_surface", "AUTOTRADER_CLIENT_POLICY_SURFACE_SCHEMA"),
    "AUTOTRADER_USER_RULE_BUNDLE_SCHEMA": (".autotrader_user_rule_bundle", "AUTOTRADER_USER_RULE_BUNDLE_SCHEMA"),
    "AUTOTRADER_CLIENT_POLICY_BUNDLE_SCHEMA": (".autotrader_client_policy_bundle", "AUTOTRADER_CLIENT_POLICY_BUNDLE_SCHEMA"),
    "AUTOTRADER_LOCAL_GUARD_EVALUATION_SCHEMA": (".autotrader_local_guard_evaluator", "AUTOTRADER_LOCAL_GUARD_EVALUATION_SCHEMA"),
    "AUTOTRADER_LLM_PARSE_HINT_SCHEMA": (".autotrader_llm_provider", "AUTOTRADER_LLM_PARSE_HINT_SCHEMA"),
    "AUTOTRADER_LLM_PROVIDER_CONFIG_SCHEMA": (".autotrader_llm_provider", "AUTOTRADER_LLM_PROVIDER_CONFIG_SCHEMA"),
    "AUTOTRADER_CHATBOT_ADVISOR_SCHEMA": (".autotrader_chatbot_advisor", "AUTOTRADER_CHATBOT_ADVISOR_SCHEMA"),
    "AUTOTRADER_CHATBOT_LANGUAGE_SCHEMA": (".autotrader_chatbot_advisor", "AUTOTRADER_CHATBOT_LANGUAGE_SCHEMA"),
    "AUTOTRADER_CHATBOT_REFINEMENT_SCHEMA": (".autotrader_chatbot_advisor", "AUTOTRADER_CHATBOT_REFINEMENT_SCHEMA"),
    "AUTOTRADER_TABULAR_Q_SCHEMA": (".autotrader_q_learning_sandbox", "AUTOTRADER_TABULAR_Q_SCHEMA"),
    "AUTOTRADER_TABULAR_Q_COMPARE_SCHEMA": (".autotrader_q_learning_sandbox", "AUTOTRADER_TABULAR_Q_COMPARE_SCHEMA"),
    "AutoTraderQLProfileComparison": (".autotrader_q_learning_sandbox", "AutoTraderQLProfileComparison"),
    "compare_autotrader_q_reward_profiles": (".autotrader_q_learning_sandbox", "compare_autotrader_q_reward_profiles"),
    "AutoTraderQLAction": (".autotrader_q_learning_sandbox", "AutoTraderQLAction"),
    "AutoTraderQLRewardProfile": (".autotrader_q_learning_sandbox", "AutoTraderQLRewardProfile"),
    "AutoTraderQLConfig": (".autotrader_q_learning_sandbox", "AutoTraderQLConfig"),
    "AutoTraderQLState": (".autotrader_q_learning_sandbox", "AutoTraderQLState"),
    "AutoTraderQLTrainingResult": (".autotrader_q_learning_sandbox", "AutoTraderQLTrainingResult"),
    "default_autotrader_q_probe_states": (".autotrader_q_learning_sandbox", "default_autotrader_q_probe_states"),
    "iter_autotrader_q_states": (".autotrader_q_learning_sandbox", "iter_autotrader_q_states"),
    "oracle_action_for_state": (".autotrader_q_learning_sandbox", "oracle_action_for_state"),
    "coarse_krr_action_for_state": (".autotrader_q_learning_sandbox", "coarse_krr_action_for_state"),
    "recommend_autotrader_q_action": (".autotrader_q_learning_sandbox", "recommend_autotrader_q_action"),
    "train_autotrader_q_table": (".autotrader_q_learning_sandbox", "train_autotrader_q_table"),
    "AutoTraderLocalGuardEvaluation": (".autotrader_local_guard_evaluator", "AutoTraderLocalGuardEvaluation"),
    "AutoTraderLocalGuardFamilyResult": (".autotrader_local_guard_evaluator", "AutoTraderLocalGuardFamilyResult"),
    "AutoTraderLocalGuardInputs": (".autotrader_local_guard_evaluator", "AutoTraderLocalGuardInputs"),
    "AutoTraderLocalLLMProviderConfig": (".autotrader_llm_provider", "AutoTraderLocalLLMProviderConfig"),
    "AutoTraderLanguageProviderResult": (".autotrader_llm_provider", "AutoTraderLanguageProviderResult"),
    "LocalOpenAICompatibleLLMProvider": (".autotrader_llm_provider", "LocalOpenAICompatibleLLMProvider"),
    "autotrader_llm_provider_config_from_dict": (".autotrader_llm_provider", "autotrader_llm_provider_config_from_dict"),
    "build_autotrader_language_provider_from_config": (".autotrader_llm_provider", "build_autotrader_language_provider_from_config"),
    "load_autotrader_llm_provider_config_file": (".autotrader_llm_provider", "load_autotrader_llm_provider_config_file"),
    "validate_autotrader_llm_parse_hint": (".autotrader_llm_provider", "validate_autotrader_llm_parse_hint"),
    "AutoTraderChatbotConfig": (".autotrader_chatbot_advisor", "AutoTraderChatbotConfig"),
    "ZenoAutoTraderChatbotAdvisor": (".autotrader_chatbot_advisor", "ZenoAutoTraderChatbotAdvisor"),
    "ZenoChatbotAdvisor": (".autotrader_chatbot_advisor", "ZenoChatbotAdvisor"),
    "autotrader_local_guard_evaluation_from_dict": (".autotrader_local_guard_evaluator", "autotrader_local_guard_evaluation_from_dict"),
    "autotrader_local_guard_inputs_from_dict": (".autotrader_local_guard_evaluator", "autotrader_local_guard_inputs_from_dict"),
    "evaluate_autotrader_local_guards": (".autotrader_local_guard_evaluator", "evaluate_autotrader_local_guards"),
    "AutoTraderClientPolicyBundle": (".autotrader_client_policy_bundle", "AutoTraderClientPolicyBundle"),
    "AutoTraderUserBudgetRule": (".autotrader_user_rule_bundle", "AutoTraderUserBudgetRule"),
    "AutoTraderUserControlRule": (".autotrader_user_rule_bundle", "AutoTraderUserControlRule"),
    "AutoTraderUserMarket": (".autotrader_user_rule_bundle", "AutoTraderUserMarket"),
    "AutoTraderUserRiskRule": (".autotrader_user_rule_bundle", "AutoTraderUserRiskRule"),
    "AutoTraderUserRuleBundle": (".autotrader_user_rule_bundle", "AutoTraderUserRuleBundle"),
    "AutoTraderUserRuleMode": (".autotrader_user_rule_bundle", "AutoTraderUserRuleMode"),
    "AutoTraderUserRulePreset": (".autotrader_user_rule_bundle", "AutoTraderUserRulePreset"),
    "AutoTraderUserSizingRule": (".autotrader_user_rule_bundle", "AutoTraderUserSizingRule"),
    "AutoTraderUserTriggerRule": (".autotrader_user_rule_bundle", "AutoTraderUserTriggerRule"),
    "AutoTraderUserWindowRule": (".autotrader_user_rule_bundle", "AutoTraderUserWindowRule"),
    "AutoTraderClientPolicySurface": (".autotrader_client_policy_surface", "AutoTraderClientPolicySurface"),
    "autotrader_client_policy_bundle_from_dict": (".autotrader_client_policy_bundle", "autotrader_client_policy_bundle_from_dict"),
    "autotrader_user_rule_bundle_from_dict": (".autotrader_user_rule_bundle", "autotrader_user_rule_bundle_from_dict"),
    "autotrader_client_policy_surface_from_dict": (".autotrader_client_policy_surface", "autotrader_client_policy_surface_from_dict"),
    "build_autotrader_client_policy_bundle": (".autotrader_client_policy_bundle", "build_autotrader_client_policy_bundle"),
    "build_autotrader_client_policy_bundle_from_user_rule_bundle": (".autotrader_user_rule_bundle", "build_autotrader_client_policy_bundle_from_user_rule_bundle"),
    "build_autotrader_client_policy_surface_from_user_rule_bundle": (".autotrader_user_rule_bundle", "build_autotrader_client_policy_surface_from_user_rule_bundle"),
    "build_autotrader_user_rule_bundle_from_mode": (".autotrader_user_rule_bundle", "build_autotrader_user_rule_bundle_from_mode"),
    "build_autotrader_user_rule_bundle_from_preset": (".autotrader_user_rule_bundle", "build_autotrader_user_rule_bundle_from_preset"),
    "build_autotrader_user_rule_source_artifact": (".autotrader_user_rule_bundle", "build_autotrader_user_rule_source_artifact"),
    "build_autotrader_client_policy_surface": (".autotrader_client_policy_surface", "build_autotrader_client_policy_surface"),
    "load_autotrader_client_policy_bundle_file": (".autotrader_client_policy_bundle", "load_autotrader_client_policy_bundle_file"),
    "load_autotrader_user_rule_bundle_file": (".autotrader_user_rule_bundle", "load_autotrader_user_rule_bundle_file"),
    "sign_autotrader_client_policy_bundle": (".autotrader_client_policy_bundle", "sign_autotrader_client_policy_bundle"),
    "verify_autotrader_client_policy_bundle_signature": (".autotrader_client_policy_bundle", "verify_autotrader_client_policy_bundle_signature"),
    "compile_autotrader_user_rule_bundle": (".autotrader_user_rule_bundle", "compile_autotrader_user_rule_bundle"),
    "dump_local_policy_document": (".local_policy", "dump_local_policy_document"),
    "load_local_policy_file": (".local_policy", "load_local_policy_file"),
    "parse_local_policy_document": (".local_policy", "parse_local_policy_document"),
    "compile_policy_candidate": (".policy_compiler", "compile_policy_candidate"),
    "PolicyTextCompilation": (".policy_text_compiler", "PolicyTextCompilation"),
    "compile_policy_text": (".policy_text_compiler", "compile_policy_text"),
    "TauPolicyReceipt": (".tau_policy_adapter", "TauPolicyReceipt"),
    "build_compile_contract_tau_policy_receipt": (
        ".tau_policy_adapter",
        "build_compile_contract_tau_policy_receipt",
    ),
    "build_budget_guard_tau_policy_receipt": (
        ".tau_policy_adapter",
        "build_budget_guard_tau_policy_receipt",
    ),
    "build_execution_guard_tau_policy_receipt": (
        ".tau_policy_adapter",
        "build_execution_guard_tau_policy_receipt",
    ),
    "build_oracle_freshness_guard_tau_policy_receipt": (
        ".tau_policy_adapter",
        "build_oracle_freshness_guard_tau_policy_receipt",
    ),
}


def __getattr__(name: str) -> Any:
    export = _LAZY_EXPORTS.get(name)
    if export is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr_name = export
    module = import_module(module_name, __name__)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value

__all__ = [
    "NotionalCaps",
    "PolicyBackend",
    "RiskLimits",
    "StrategyAction",
    "StrategyControls",
    "StrategyIR",
    "StrategyTemplate",
    "StrategyWindow",
    "TauPolicyReceipt",
    "AUTOTRADER_KRR_DEFAULT_BACKEND",
    "AUTOTRADER_CLIENT_POLICY_BUNDLE_SCHEMA",
    "AUTOTRADER_USER_RULE_BUNDLE_SCHEMA",
    "AUTOTRADER_CLIENT_POLICY_SURFACE_SCHEMA",
    "AUTOTRADER_LOCAL_GUARD_EVALUATION_SCHEMA",
    "AUTOTRADER_LLM_PARSE_HINT_SCHEMA",
    "AUTOTRADER_LLM_PROVIDER_CONFIG_SCHEMA",
    "AUTOTRADER_CHATBOT_ADVISOR_SCHEMA",
    "AUTOTRADER_CHATBOT_LANGUAGE_SCHEMA",
    "AUTOTRADER_CHATBOT_REFINEMENT_SCHEMA",
    "AutoTraderLocalGuardEvaluation",
    "AutoTraderLocalGuardFamilyResult",
    "AutoTraderLocalGuardInputs",
    "AutoTraderLocalLLMProviderConfig",
    "AutoTraderLanguageProviderResult",
    "LocalOpenAICompatibleLLMProvider",
    "AutoTraderChatbotConfig",
    "ZenoAutoTraderChatbotAdvisor",
    "ZenoChatbotAdvisor",
    "AUTOTRADER_TABULAR_Q_SCHEMA",
    "AUTOTRADER_TABULAR_Q_COMPARE_SCHEMA",
    "AutoTraderQLProfileComparison",
    "AutoTraderQLAction",
    "AutoTraderQLRewardProfile",
    "AutoTraderQLConfig",
    "AutoTraderQLState",
    "AutoTraderQLTrainingResult",
    "AUTOTRADER_KRR_SCHEMA",
    "AutoTraderClientPolicyBundle",
    "AutoTraderUserBudgetRule",
    "AutoTraderUserControlRule",
    "AutoTraderUserMarket",
    "AutoTraderUserRiskRule",
    "AutoTraderUserRuleBundle",
    "AutoTraderUserRuleMode",
    "AutoTraderUserRulePreset",
    "AutoTraderUserSizingRule",
    "AutoTraderUserTriggerRule",
    "AutoTraderUserWindowRule",
    "AutoTraderClientPolicySurface",
    "advise_autotrader_krr",
    "autotrader_client_policy_bundle_from_dict",
    "autotrader_user_rule_bundle_from_dict",
    "autotrader_client_policy_surface_from_dict",
    "autotrader_local_guard_evaluation_from_dict",
    "autotrader_local_guard_inputs_from_dict",
    "default_autotrader_q_probe_states",
    "compare_autotrader_q_reward_profiles",
    "iter_autotrader_q_states",
    "oracle_action_for_state",
    "coarse_krr_action_for_state",
    "autotrader_krr_check_options",
    "autotrader_krr_semantic_signature",
    "build_autotrader_client_policy_bundle",
    "build_autotrader_client_policy_bundle_from_user_rule_bundle",
    "build_autotrader_client_policy_surface_from_user_rule_bundle",
    "build_autotrader_user_rule_bundle_from_mode",
    "build_autotrader_user_rule_bundle_from_preset",
    "build_autotrader_user_rule_source_artifact",
    "build_autotrader_client_policy_surface",
    "recommend_autotrader_q_action",
    "train_autotrader_q_table",
    "evaluate_autotrader_local_guards",
    "autotrader_llm_provider_config_from_dict",
    "build_autotrader_language_provider_from_config",
    "load_autotrader_llm_provider_config_file",
    "validate_autotrader_llm_parse_hint",
    "build_autotrader_krr_history",
    "build_compile_contract_tau_policy_receipt",
    "build_budget_guard_tau_policy_receipt",
    "build_execution_guard_tau_policy_receipt",
    "build_oracle_freshness_guard_tau_policy_receipt",
    "compile_policy_candidate",
    "compile_policy_text",
    "create_swap_intent",
    "dump_local_policy_document",
    "sign_intent",
    "PolicyTextCompilation",
    "load_autotrader_client_policy_bundle_file",
    "load_autotrader_user_rule_bundle_file",
    "load_local_policy_file",
    "parse_local_policy_document",
    "sign_autotrader_client_policy_bundle",
    "verify_autotrader_client_policy_bundle_signature",
    "compile_autotrader_user_rule_bundle",
    "verify_intent_signature",
    "batch_intents",
    "create_batch",
]
