"""
Auto-generated Python reference model for: fire_lp_loss_cover_v1
IR hash: sha256:bf1509a7c86dfd9cd2d353133de9abf879f2fdf2279c4bd3114636233e8e7be4

Generated by ESSO (Evolutionary Spec Search Optimizer)

This file is standalone and has no ESSO dependencies.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal, Mapping


# Domain enums
PHASE_SYMBOLS = ('Idle', 'Compiled', 'Settled')


@dataclass(frozen=True)
class State:
    """Model state."""
    artifact_lower: int
    artifact_upper: int
    cap_amount: int
    deductible: int
    hodl_lower: int
    hodl_upper: int
    holder_delta: int
    holder_posted: int
    lpv_lower: int
    lpv_upper: int
    n_notional: int
    phase: str
    witness_hodl_final: int
    witness_lpv_final: int
    writer_delta: int
    writer_posted: int


@dataclass(frozen=True)
class Command:
    """Command to execute."""
    tag: Literal('compile_lp_loss_cover', 'firev_accept_and_settle')
    args: Mapping[str, Any]


@dataclass(frozen=True)
class StepResult:
    """Result of a step execution."""
    ok: bool
    state: State | None = None
    effects: Mapping[str, Any] | None = None
    error: str | None = None


def init_state() -> State:
    """Return the initial state."""
    return State(
        artifact_lower=0,
        artifact_upper=0,
        cap_amount=0,
        deductible=0,
        hodl_lower=0,
        hodl_upper=0,
        holder_delta=0,
        holder_posted=0,
        lpv_lower=0,
        lpv_upper=0,
        n_notional=0,
        phase='Idle',
        witness_hodl_final=0,
        witness_lpv_final=0,
        writer_delta=0,
        writer_posted=0,
    )


def check_invariants(s: State) -> tuple[bool, str | None]:
    """Check all invariants. Returns (ok, first_failed_id)."""
    if not (isinstance(s.artifact_lower, int) and not isinstance(s.artifact_lower, bool) and 0 <= s.artifact_lower <= 0):
        return False, 'domain_artifact_lower'
    if not (isinstance(s.artifact_upper, int) and not isinstance(s.artifact_upper, bool) and 0 <= s.artifact_upper <= 1000000):
        return False, 'domain_artifact_upper'
    if not (isinstance(s.cap_amount, int) and not isinstance(s.cap_amount, bool) and 0 <= s.cap_amount <= 1000):
        return False, 'domain_cap_amount'
    if not (isinstance(s.deductible, int) and not isinstance(s.deductible, bool) and 0 <= s.deductible <= 1000):
        return False, 'domain_deductible'
    if not (isinstance(s.hodl_lower, int) and not isinstance(s.hodl_lower, bool) and 0 <= s.hodl_lower <= 1000):
        return False, 'domain_hodl_lower'
    if not (isinstance(s.hodl_upper, int) and not isinstance(s.hodl_upper, bool) and 0 <= s.hodl_upper <= 1000):
        return False, 'domain_hodl_upper'
    if not (isinstance(s.holder_delta, int) and not isinstance(s.holder_delta, bool) and 0 <= s.holder_delta <= 1000000):
        return False, 'domain_holder_delta'
    if not (isinstance(s.holder_posted, int) and not isinstance(s.holder_posted, bool) and 0 <= s.holder_posted <= 1000000):
        return False, 'domain_holder_posted'
    if not (isinstance(s.lpv_lower, int) and not isinstance(s.lpv_lower, bool) and 0 <= s.lpv_lower <= 1000):
        return False, 'domain_lpv_lower'
    if not (isinstance(s.lpv_upper, int) and not isinstance(s.lpv_upper, bool) and 0 <= s.lpv_upper <= 1000):
        return False, 'domain_lpv_upper'
    if not (isinstance(s.n_notional, int) and not isinstance(s.n_notional, bool) and 0 <= s.n_notional <= 1000):
        return False, 'domain_n_notional'
    if not (s.phase in ('Idle', 'Compiled', 'Settled')):
        return False, 'domain_phase'
    if not (isinstance(s.witness_hodl_final, int) and not isinstance(s.witness_hodl_final, bool) and 0 <= s.witness_hodl_final <= 1000):
        return False, 'domain_witness_hodl_final'
    if not (isinstance(s.witness_lpv_final, int) and not isinstance(s.witness_lpv_final, bool) and 0 <= s.witness_lpv_final <= 1000):
        return False, 'domain_witness_lpv_final'
    if not (isinstance(s.writer_delta, int) and not isinstance(s.writer_delta, bool) and -1000000 <= s.writer_delta <= 0):
        return False, 'domain_writer_delta'
    if not (isinstance(s.writer_posted, int) and not isinstance(s.writer_posted, bool) and 0 <= s.writer_posted <= 1000000):
        return False, 'domain_writer_posted'
    if not ((True if ('Idle' == s.phase) else (0 == s.artifact_lower))):
        return False, 'inv_compiled_lower_is_zero'
    if not ((True if ('Idle' == s.phase) else ((((s.cap_amount if (((s.hodl_upper - s.lpv_lower) - s.deductible) >= s.cap_amount) else ((s.hodl_upper - s.lpv_lower) - s.deductible)) if (s.hodl_upper >= (s.deductible + s.lpv_lower)) else 0) * s.n_notional) == s.artifact_upper))):
        return False, 'inv_compiled_upper_matches_bound'
    if not (((0 == (s.holder_delta + s.writer_delta)) if ('Settled' == s.phase) else True)):
        return False, 'inv_delta_conservation'
    if not ((s.hodl_lower <= s.hodl_upper)):
        return False, 'inv_hodl_interval_well_formed'
    if not ((((s.holder_delta + s.holder_posted) >= 0) if ('Settled' == s.phase) else True)):
        return False, 'inv_holder_solvent_after_accept'
    if not ((s.lpv_lower <= s.lpv_upper)):
        return False, 'inv_lpv_interval_well_formed'
    if not (((s.holder_delta <= s.artifact_upper) if ('Settled' == s.phase) else True)):
        return False, 'inv_settled_holder_delta_bounded'
    if not (((s.holder_delta >= 0) if ('Settled' == s.phase) else True)):
        return False, 'inv_settled_holder_delta_nonnegative'
    if not ((((0 - s.holder_delta) == s.writer_delta) if ('Settled' == s.phase) else True)):
        return False, 'inv_settled_writer_is_neg_holder'
    if not ((((s.writer_delta + s.writer_posted) >= 0) if ('Settled' == s.phase) else True)):
        return False, 'inv_writer_solvent_after_accept'
    return True, None


def step(s: State, cmd: Command) -> StepResult:
    """Execute a step. Returns StepResult."""
    # Check pre-state invariants
    ok, failed = check_invariants(s)
    if not ok:
        return StepResult(ok=False, error=f'pre-invariant violated: {failed}')

    if cmd.tag == 'compile_lp_loss_cover':
        if 'n_in' not in cmd.args or not (isinstance(cmd.args['n_in'], int) and not isinstance(cmd.args['n_in'], bool) and 0 <= cmd.args['n_in'] <= 1000):
            return StepResult(ok=False, error='invalid param n_in')
        if 'deductible_in' not in cmd.args or not (isinstance(cmd.args['deductible_in'], int) and not isinstance(cmd.args['deductible_in'], bool) and 0 <= cmd.args['deductible_in'] <= 1000):
            return StepResult(ok=False, error='invalid param deductible_in')
        if 'cap_in' not in cmd.args or not (isinstance(cmd.args['cap_in'], int) and not isinstance(cmd.args['cap_in'], bool) and 0 <= cmd.args['cap_in'] <= 1000):
            return StepResult(ok=False, error='invalid param cap_in')
        if 'hodl_lower_in' not in cmd.args or not (isinstance(cmd.args['hodl_lower_in'], int) and not isinstance(cmd.args['hodl_lower_in'], bool) and 0 <= cmd.args['hodl_lower_in'] <= 1000):
            return StepResult(ok=False, error='invalid param hodl_lower_in')
        if 'hodl_upper_in' not in cmd.args or not (isinstance(cmd.args['hodl_upper_in'], int) and not isinstance(cmd.args['hodl_upper_in'], bool) and 0 <= cmd.args['hodl_upper_in'] <= 1000):
            return StepResult(ok=False, error='invalid param hodl_upper_in')
        if 'lpv_lower_in' not in cmd.args or not (isinstance(cmd.args['lpv_lower_in'], int) and not isinstance(cmd.args['lpv_lower_in'], bool) and 0 <= cmd.args['lpv_lower_in'] <= 1000):
            return StepResult(ok=False, error='invalid param lpv_lower_in')
        if 'lpv_upper_in' not in cmd.args or not (isinstance(cmd.args['lpv_upper_in'], int) and not isinstance(cmd.args['lpv_upper_in'], bool) and 0 <= cmd.args['lpv_upper_in'] <= 1000):
            return StepResult(ok=False, error='invalid param lpv_upper_in')
        if not (((cmd.args['hodl_lower_in'] <= cmd.args['hodl_upper_in']) and (cmd.args['lpv_lower_in'] <= cmd.args['lpv_upper_in']) and ('Idle' == s.phase))):
            return StepResult(ok=False, error='guard failed for compile_lp_loss_cover')
        # Compute updates (simultaneous)
        new_state = State(
            artifact_lower=0,
            artifact_upper=(((cmd.args['cap_in'] if (((cmd.args['hodl_upper_in'] - cmd.args['lpv_lower_in']) - cmd.args['deductible_in']) >= cmd.args['cap_in']) else ((cmd.args['hodl_upper_in'] - cmd.args['lpv_lower_in']) - cmd.args['deductible_in'])) if (cmd.args['hodl_upper_in'] >= (cmd.args['deductible_in'] + cmd.args['lpv_lower_in'])) else 0) * cmd.args['n_in']),
            cap_amount=cmd.args['cap_in'],
            deductible=cmd.args['deductible_in'],
            hodl_lower=cmd.args['hodl_lower_in'],
            hodl_upper=cmd.args['hodl_upper_in'],
            holder_delta=s.holder_delta,
            holder_posted=s.holder_posted,
            lpv_lower=cmd.args['lpv_lower_in'],
            lpv_upper=cmd.args['lpv_upper_in'],
            n_notional=cmd.args['n_in'],
            phase='Compiled',
            witness_hodl_final=s.witness_hodl_final,
            witness_lpv_final=s.witness_lpv_final,
            writer_delta=s.writer_delta,
            writer_posted=s.writer_posted,
        )
        effects = {
            'compiled_upper': new_state.artifact_upper,
            'firev_accept': False,
            'payoff_out': 0,
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'firev_accept_and_settle':
        if 'witness_hodl_final_in' not in cmd.args or not (isinstance(cmd.args['witness_hodl_final_in'], int) and not isinstance(cmd.args['witness_hodl_final_in'], bool) and 0 <= cmd.args['witness_hodl_final_in'] <= 1000):
            return StepResult(ok=False, error='invalid param witness_hodl_final_in')
        if 'witness_lpv_final_in' not in cmd.args or not (isinstance(cmd.args['witness_lpv_final_in'], int) and not isinstance(cmd.args['witness_lpv_final_in'], bool) and 0 <= cmd.args['witness_lpv_final_in'] <= 1000):
            return StepResult(ok=False, error='invalid param witness_lpv_final_in')
        if 'holder_posted_in' not in cmd.args or not (isinstance(cmd.args['holder_posted_in'], int) and not isinstance(cmd.args['holder_posted_in'], bool) and 0 <= cmd.args['holder_posted_in'] <= 1000000):
            return StepResult(ok=False, error='invalid param holder_posted_in')
        if 'writer_posted_in' not in cmd.args or not (isinstance(cmd.args['writer_posted_in'], int) and not isinstance(cmd.args['writer_posted_in'], bool) and 0 <= cmd.args['writer_posted_in'] <= 1000000):
            return StepResult(ok=False, error='invalid param writer_posted_in')
        if not (((cmd.args['witness_hodl_final_in'] <= s.hodl_upper) and (cmd.args['witness_lpv_final_in'] <= s.lpv_upper) and (s.hodl_lower <= cmd.args['witness_hodl_final_in']) and (s.lpv_lower <= cmd.args['witness_lpv_final_in']) and ('Compiled' == s.phase) and (cmd.args['holder_posted_in'] >= s.artifact_lower) and (cmd.args['writer_posted_in'] >= s.artifact_upper))):
            return StepResult(ok=False, error='guard failed for firev_accept_and_settle')
        # Compute updates (simultaneous)
        new_state = State(
            artifact_lower=s.artifact_lower,
            artifact_upper=s.artifact_upper,
            cap_amount=s.cap_amount,
            deductible=s.deductible,
            hodl_lower=s.hodl_lower,
            hodl_upper=s.hodl_upper,
            holder_delta=(((s.cap_amount if (((cmd.args['witness_hodl_final_in'] - cmd.args['witness_lpv_final_in']) - s.deductible) >= s.cap_amount) else ((cmd.args['witness_hodl_final_in'] - cmd.args['witness_lpv_final_in']) - s.deductible)) if (cmd.args['witness_hodl_final_in'] >= (cmd.args['witness_lpv_final_in'] + s.deductible)) else 0) * s.n_notional),
            holder_posted=cmd.args['holder_posted_in'],
            lpv_lower=s.lpv_lower,
            lpv_upper=s.lpv_upper,
            n_notional=s.n_notional,
            phase='Settled',
            witness_hodl_final=cmd.args['witness_hodl_final_in'],
            witness_lpv_final=cmd.args['witness_lpv_final_in'],
            writer_delta=(0 - (((s.cap_amount if (((cmd.args['witness_hodl_final_in'] - cmd.args['witness_lpv_final_in']) - s.deductible) >= s.cap_amount) else ((cmd.args['witness_hodl_final_in'] - cmd.args['witness_lpv_final_in']) - s.deductible)) if (cmd.args['witness_hodl_final_in'] >= (cmd.args['witness_lpv_final_in'] + s.deductible)) else 0) * s.n_notional)),
            writer_posted=cmd.args['writer_posted_in'],
        )
        effects = {
            'compiled_upper': new_state.artifact_upper,
            'firev_accept': True,
            'payoff_out': new_state.holder_delta,
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    else:
        return StepResult(ok=False, error=f'unknown action: {cmd.tag}')


# === Hypothesis test scaffolding ===
# Uncomment and install hypothesis to use property-based testing

# from hypothesis import given, strategies as st
# from hypothesis.stateful import RuleBasedStateMachine, rule, initialize
#
# class ModelStateMachine(RuleBasedStateMachine):
#     def __init__(self):
#         super().__init__()
#         self.state = init_state()
#
#     @initialize()
#     def init(self):
#         self.state = init_state()
#         ok, _ = check_invariants(self.state)
#         assert ok, 'init violates invariants'
#
#     # @rule(n_in=st.integers(), deductible_in=st.integers(), cap_in=st.integers(), hodl_lower_in=st.integers(), hodl_upper_in=st.integers(), lpv_lower_in=st.integers(), lpv_upper_in=st.integers())
#     # def compile_lp_loss_cover(self, n_in, deductible_in, cap_in, hodl_lower_in, hodl_upper_in, lpv_lower_in, lpv_upper_in):
#     #     cmd = Command(tag='compile_lp_loss_cover', args={'n_in': n_in, 'deductible_in': deductible_in, 'cap_in': cap_in, 'hodl_lower_in': hodl_lower_in, 'hodl_upper_in': hodl_upper_in, 'lpv_lower_in': lpv_lower_in, 'lpv_upper_in': lpv_upper_in})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule(witness_hodl_final_in=st.integers(), witness_lpv_final_in=st.integers(), holder_posted_in=st.integers(), writer_posted_in=st.integers())
#     # def firev_accept_and_settle(self, witness_hodl_final_in, witness_lpv_final_in, holder_posted_in, writer_posted_in):
#     #     cmd = Command(tag='firev_accept_and_settle', args={'witness_hodl_final_in': witness_hodl_final_in, 'witness_lpv_final_in': witness_lpv_final_in, 'holder_posted_in': holder_posted_in, 'writer_posted_in': writer_posted_in})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
# TestModel = ModelStateMachine.TestCase


def replay_trace(commands: list[tuple[str, dict[str, Any]]]) -> list[StepResult]:
    """Replay a trace of commands and return results."""
    results: list[StepResult] = []
    s = init_state()
    for tag, args in commands:
        cmd = Command(tag=tag, args=args)
        result = step(s, cmd)
        results.append(result)
        if result.ok and result.state is not None:
            s = result.state
        else:
            break
    return results


if __name__ == '__main__':
    # Quick sanity check
    s0 = init_state()
    ok, failed = check_invariants(s0)
    print(f'Initial state: {s0}')
    print(f'Invariants OK: {ok}')
    if not ok:
        print(f'  Failed: {failed}')
