"""
Auto-generated Python reference model for: fire_lp_loss_cover_v1
IR hash: sha256:bf1509a7c86dfd9cd2d353133de9abf879f2fdf2279c4bd3114636233e8e7be4

Generated by ESSO (Evolutionary Spec Search Optimizer)

This file is standalone and has no ESSO dependencies.

NOTE: the bodies of check_invariants/step were manually refactored for
complexity (helpers extracted; semantics unchanged). Observable behavior is
pinned byte-for-byte by tests/kernels/test_fire_lp_loss_cover_v1_ref_characterization.py
and its committed corpus. If this file is ever regenerated from the IR, rerun
that corpus before committing.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal, Mapping


# Domain enums
PHASE_SYMBOLS = ('Idle', 'Compiled', 'Settled')


@dataclass(frozen=True)
class State:
    """Model state."""
    artifact_lower: int
    artifact_upper: int
    cap_amount: int
    deductible: int
    hodl_lower: int
    hodl_upper: int
    holder_delta: int
    holder_posted: int
    lpv_lower: int
    lpv_upper: int
    n_notional: int
    phase: str
    witness_hodl_final: int
    witness_lpv_final: int
    writer_delta: int
    writer_posted: int


@dataclass(frozen=True)
class Command:
    """Command to execute."""
    tag: Literal('compile_lp_loss_cover', 'firev_accept_and_settle')
    args: Mapping[str, Any]


@dataclass(frozen=True)
class StepResult:
    """Result of a step execution."""
    ok: bool
    state: State | None = None
    effects: Mapping[str, Any] | None = None
    error: str | None = None


def init_state() -> State:
    """Return the initial state."""
    return State(
        artifact_lower=0,
        artifact_upper=0,
        cap_amount=0,
        deductible=0,
        hodl_lower=0,
        hodl_upper=0,
        holder_delta=0,
        holder_posted=0,
        lpv_lower=0,
        lpv_upper=0,
        n_notional=0,
        phase='Idle',
        witness_hodl_final=0,
        witness_lpv_final=0,
        writer_delta=0,
        writer_posted=0,
    )


def _is_int_in_range(value: Any, lo: int, hi: int) -> bool:
    """The generated domain predicate: a non-bool int within [lo, hi]."""
    return isinstance(value, int) and not isinstance(value, bool) and lo <= value <= hi


def _implies(premise: bool, conclusion: bool) -> bool:
    """Material implication; `conclusion` is evaluated eagerly by the caller."""
    return (not premise) or conclusion


def _capped_excess(hodl: int, lpv: int, deductible: int, cap: int) -> int:
    """The generated payoff-per-notional term.

    min(cap, (hodl - lpv) - deductible) when hodl >= deductible + lpv, else 0.
    Used for compile's artifact_upper bound and settle's payoff (and the
    inv_compiled_upper_matches_bound recomputation).
    """
    if not (hodl >= (deductible + lpv)):
        return 0
    excess = (hodl - lpv) - deductible
    return cap if excess >= cap else excess


def _first_domain_violation(s: State) -> str | None:
    """First failed domain invariant id, in the generated check order.

    Each row's predicate is total for arbitrary field values (the isinstance
    guard inside _is_int_in_range runs before any comparison), so building the
    row tuple eagerly cannot raise and preserves the original first-failure id.
    """
    checks = (
        (_is_int_in_range(s.artifact_lower, 0, 0), 'domain_artifact_lower'),
        (_is_int_in_range(s.artifact_upper, 0, 1000000), 'domain_artifact_upper'),
        (_is_int_in_range(s.cap_amount, 0, 1000), 'domain_cap_amount'),
        (_is_int_in_range(s.deductible, 0, 1000), 'domain_deductible'),
        (_is_int_in_range(s.hodl_lower, 0, 1000), 'domain_hodl_lower'),
        (_is_int_in_range(s.hodl_upper, 0, 1000), 'domain_hodl_upper'),
        (_is_int_in_range(s.holder_delta, 0, 1000000), 'domain_holder_delta'),
        (_is_int_in_range(s.holder_posted, 0, 1000000), 'domain_holder_posted'),
        (_is_int_in_range(s.lpv_lower, 0, 1000), 'domain_lpv_lower'),
        (_is_int_in_range(s.lpv_upper, 0, 1000), 'domain_lpv_upper'),
        (_is_int_in_range(s.n_notional, 0, 1000), 'domain_n_notional'),
        (s.phase in PHASE_SYMBOLS, 'domain_phase'),
        (_is_int_in_range(s.witness_hodl_final, 0, 1000), 'domain_witness_hodl_final'),
        (_is_int_in_range(s.witness_lpv_final, 0, 1000), 'domain_witness_lpv_final'),
        (_is_int_in_range(s.writer_delta, -1000000, 0), 'domain_writer_delta'),
        (_is_int_in_range(s.writer_posted, 0, 1000000), 'domain_writer_posted'),
    )
    for ok, invariant_id in checks:
        if not ok:
            return invariant_id
    return None


def _first_semantic_violation(s: State) -> str | None:
    """First failed semantic invariant id, in the generated check order.

    Caller contract: the domain checks have already passed, so every field is
    a bounded int and phase is a PHASE_SYMBOLS member; every expression below
    is therefore total and may be evaluated eagerly without changing behavior.
    """
    non_idle = s.phase != 'Idle'
    settled = s.phase == 'Settled'
    expected_upper = _capped_excess(s.hodl_upper, s.lpv_lower, s.deductible, s.cap_amount) * s.n_notional
    checks = (
        (_implies(non_idle, 0 == s.artifact_lower), 'inv_compiled_lower_is_zero'),
        (_implies(non_idle, expected_upper == s.artifact_upper), 'inv_compiled_upper_matches_bound'),
        (_implies(settled, 0 == (s.holder_delta + s.writer_delta)), 'inv_delta_conservation'),
        (s.hodl_lower <= s.hodl_upper, 'inv_hodl_interval_well_formed'),
        (_implies(settled, (s.holder_delta + s.holder_posted) >= 0), 'inv_holder_solvent_after_accept'),
        (s.lpv_lower <= s.lpv_upper, 'inv_lpv_interval_well_formed'),
        (_implies(settled, s.holder_delta <= s.artifact_upper), 'inv_settled_holder_delta_bounded'),
        (_implies(settled, s.holder_delta >= 0), 'inv_settled_holder_delta_nonnegative'),
        (_implies(settled, (0 - s.holder_delta) == s.writer_delta), 'inv_settled_writer_is_neg_holder'),
        (_implies(settled, (s.writer_delta + s.writer_posted) >= 0), 'inv_writer_solvent_after_accept'),
    )
    for ok, invariant_id in checks:
        if not ok:
            return invariant_id
    return None


def check_invariants(s: State) -> tuple[bool, str | None]:
    """Check all invariants. Returns (ok, first_failed_id)."""
    failed = _first_domain_violation(s)
    if failed is None:
        failed = _first_semantic_violation(s)
    if failed is None:
        return True, None
    return False, failed


_COMPILE_PARAM_SPECS: tuple[tuple[str, int, int], ...] = (
    ('n_in', 0, 1000),
    ('deductible_in', 0, 1000),
    ('cap_in', 0, 1000),
    ('hodl_lower_in', 0, 1000),
    ('hodl_upper_in', 0, 1000),
    ('lpv_lower_in', 0, 1000),
    ('lpv_upper_in', 0, 1000),
)

_SETTLE_PARAM_SPECS: tuple[tuple[str, int, int], ...] = (
    ('witness_hodl_final_in', 0, 1000),
    ('witness_lpv_final_in', 0, 1000),
    ('holder_posted_in', 0, 1000000),
    ('writer_posted_in', 0, 1000000),
)


def _read_int_param(args: Mapping[str, Any], name: str, lo: int, hi: int) -> tuple[bool, int]:
    """Validate args[name] as a non-bool int in [lo, hi]; return (ok, value).

    Membership is tested before the single read, matching the generated
    `name not in args or not (...)` short-circuit.
    """
    if name not in args:
        return False, 0
    value = args[name]
    if not _is_int_in_range(value, lo, hi):
        return False, 0
    return True, value


def _read_params(
    args: Mapping[str, Any], specs: tuple[tuple[str, int, int], ...]
) -> tuple[dict[str, int] | None, str | None]:
    """Read params in spec order; the first invalid one wins (generated order).

    Validated values are threaded forward so the command mapping is read at
    most once per parameter.
    """
    values: dict[str, int] = {}
    for name, lo, hi in specs:
        ok, value = _read_int_param(args, name, lo, hi)
        if not ok:
            return None, f'invalid param {name}'
        values[name] = value
    return values, None


def _checked_accept(new_state: State, effects: Mapping[str, Any]) -> StepResult:
    """Fail closed on post-invariants; otherwise accept with effects."""
    ok, failed = check_invariants(new_state)
    if not ok:
        return StepResult(ok=False, error=f'post-invariant violated: {failed}')
    return StepResult(ok=True, state=new_state, effects=effects)


def _step_compile_lp_loss_cover(s: State, args: Mapping[str, Any]) -> StepResult:
    """Param validation, guard, compute, and post-check for compile_lp_loss_cover."""
    params, error = _read_params(args, _COMPILE_PARAM_SPECS)
    if params is None:
        return StepResult(ok=False, error=error)
    if not (
        params['hodl_lower_in'] <= params['hodl_upper_in']
        and params['lpv_lower_in'] <= params['lpv_upper_in']
        and 'Idle' == s.phase
    ):
        return StepResult(ok=False, error='guard failed for compile_lp_loss_cover')
    # Compute updates (simultaneous)
    compiled_upper = (
        _capped_excess(
            params['hodl_upper_in'], params['lpv_lower_in'], params['deductible_in'], params['cap_in']
        )
        * params['n_in']
    )
    new_state = State(
        artifact_lower=0,
        artifact_upper=compiled_upper,
        cap_amount=params['cap_in'],
        deductible=params['deductible_in'],
        hodl_lower=params['hodl_lower_in'],
        hodl_upper=params['hodl_upper_in'],
        holder_delta=s.holder_delta,
        holder_posted=s.holder_posted,
        lpv_lower=params['lpv_lower_in'],
        lpv_upper=params['lpv_upper_in'],
        n_notional=params['n_in'],
        phase='Compiled',
        witness_hodl_final=s.witness_hodl_final,
        witness_lpv_final=s.witness_lpv_final,
        writer_delta=s.writer_delta,
        writer_posted=s.writer_posted,
    )
    effects = {
        'compiled_upper': new_state.artifact_upper,
        'firev_accept': False,
        'payoff_out': 0,
    }
    return _checked_accept(new_state, effects)


def _step_firev_accept_and_settle(s: State, args: Mapping[str, Any]) -> StepResult:
    """Param validation, guard, compute, and post-check for firev_accept_and_settle."""
    params, error = _read_params(args, _SETTLE_PARAM_SPECS)
    if params is None:
        return StepResult(ok=False, error=error)
    witness_hodl = params['witness_hodl_final_in']
    witness_lpv = params['witness_lpv_final_in']
    if not (
        witness_hodl <= s.hodl_upper
        and witness_lpv <= s.lpv_upper
        and s.hodl_lower <= witness_hodl
        and s.lpv_lower <= witness_lpv
        and 'Compiled' == s.phase
        and params['holder_posted_in'] >= s.artifact_lower
        and params['writer_posted_in'] >= s.artifact_upper
    ):
        return StepResult(ok=False, error='guard failed for firev_accept_and_settle')
    # Compute updates (simultaneous)
    payoff = _capped_excess(witness_hodl, witness_lpv, s.deductible, s.cap_amount) * s.n_notional
    new_state = State(
        artifact_lower=s.artifact_lower,
        artifact_upper=s.artifact_upper,
        cap_amount=s.cap_amount,
        deductible=s.deductible,
        hodl_lower=s.hodl_lower,
        hodl_upper=s.hodl_upper,
        holder_delta=payoff,
        holder_posted=params['holder_posted_in'],
        lpv_lower=s.lpv_lower,
        lpv_upper=s.lpv_upper,
        n_notional=s.n_notional,
        phase='Settled',
        witness_hodl_final=witness_hodl,
        witness_lpv_final=witness_lpv,
        writer_delta=0 - payoff,
        writer_posted=params['writer_posted_in'],
    )
    effects = {
        'compiled_upper': new_state.artifact_upper,
        'firev_accept': True,
        'payoff_out': new_state.holder_delta,
    }
    return _checked_accept(new_state, effects)


def step(s: State, cmd: Command) -> StepResult:
    """Execute a step. Returns StepResult."""
    # Check pre-state invariants
    ok, failed = check_invariants(s)
    if not ok:
        return StepResult(ok=False, error=f'pre-invariant violated: {failed}')

    if cmd.tag == 'compile_lp_loss_cover':
        return _step_compile_lp_loss_cover(s, cmd.args)
    if cmd.tag == 'firev_accept_and_settle':
        return _step_firev_accept_and_settle(s, cmd.args)
    return StepResult(ok=False, error=f'unknown action: {cmd.tag}')


# === Hypothesis test scaffolding ===
# Uncomment and install hypothesis to use property-based testing

# from hypothesis import given, strategies as st
# from hypothesis.stateful import RuleBasedStateMachine, rule, initialize
#
# class ModelStateMachine(RuleBasedStateMachine):
#     def __init__(self):
#         super().__init__()
#         self.state = init_state()
#
#     @initialize()
#     def init(self):
#         self.state = init_state()
#         ok, _ = check_invariants(self.state)
#         assert ok, 'init violates invariants'
#
#     # @rule(n_in=st.integers(), deductible_in=st.integers(), cap_in=st.integers(), hodl_lower_in=st.integers(), hodl_upper_in=st.integers(), lpv_lower_in=st.integers(), lpv_upper_in=st.integers())
#     # def compile_lp_loss_cover(self, n_in, deductible_in, cap_in, hodl_lower_in, hodl_upper_in, lpv_lower_in, lpv_upper_in):
#     #     cmd = Command(tag='compile_lp_loss_cover', args={'n_in': n_in, 'deductible_in': deductible_in, 'cap_in': cap_in, 'hodl_lower_in': hodl_lower_in, 'hodl_upper_in': hodl_upper_in, 'lpv_lower_in': lpv_lower_in, 'lpv_upper_in': lpv_upper_in})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule(witness_hodl_final_in=st.integers(), witness_lpv_final_in=st.integers(), holder_posted_in=st.integers(), writer_posted_in=st.integers())
#     # def firev_accept_and_settle(self, witness_hodl_final_in, witness_lpv_final_in, holder_posted_in, writer_posted_in):
#     #     cmd = Command(tag='firev_accept_and_settle', args={'witness_hodl_final_in': witness_hodl_final_in, 'witness_lpv_final_in': witness_lpv_final_in, 'holder_posted_in': holder_posted_in, 'writer_posted_in': writer_posted_in})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
# TestModel = ModelStateMachine.TestCase


def replay_trace(commands: list[tuple[str, dict[str, Any]]]) -> list[StepResult]:
    """Replay a trace of commands and return results."""
    results: list[StepResult] = []
    s = init_state()
    for tag, args in commands:
        cmd = Command(tag=tag, args=args)
        result = step(s, cmd)
        results.append(result)
        if result.ok and result.state is not None:
            s = result.state
        else:
            break
    return results


if __name__ == '__main__':
    # Quick sanity check
    s0 = init_state()
    ok, failed = check_invariants(s0)
    print(f'Initial state: {s0}')
    print(f'Invariants OK: {ok}')
    if not ok:
        print(f'  Failed: {failed}')
