"""
Auto-generated Python reference model for: fire_fee_note_v1
IR hash: sha256:1d2740320070d63cc487bbc9333d10ca0d6c43e102ac1940bc4daa517a0492ba

Generated by ESSO (Evolutionary Spec Search Optimizer)

This file is standalone and has no ESSO dependencies.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal, Mapping


# Domain enums
PHASE_SYMBOLS = ('Idle', 'Compiled', 'Settled')


@dataclass(frozen=True)
class State:
    """Model state."""
    artifact_lower: int
    artifact_upper: int
    cap_index: int
    holder_delta: int
    holder_posted: int
    n_notional: int
    phase: str
    source_upper: int
    witness_final: int
    writer_delta: int
    writer_posted: int


@dataclass(frozen=True)
class Command:
    """Command to execute."""
    tag: Literal('compile_fee_note', 'firev_accept_and_settle')
    args: Mapping[str, Any]


@dataclass(frozen=True)
class StepResult:
    """Result of a step execution."""
    ok: bool
    state: State | None = None
    effects: Mapping[str, Any] | None = None
    error: str | None = None


def init_state() -> State:
    """Return the initial state."""
    return State(
        artifact_lower=0,
        artifact_upper=0,
        cap_index=0,
        holder_delta=0,
        holder_posted=0,
        n_notional=0,
        phase='Idle',
        source_upper=0,
        witness_final=0,
        writer_delta=0,
        writer_posted=0,
    )


def check_invariants(s: State) -> tuple[bool, str | None]:
    """Check all invariants. Returns (ok, first_failed_id)."""
    if not (isinstance(s.artifact_lower, int) and not isinstance(s.artifact_lower, bool) and 0 <= s.artifact_lower <= 0):
        return False, 'domain_artifact_lower'
    if not (isinstance(s.artifact_upper, int) and not isinstance(s.artifact_upper, bool) and 0 <= s.artifact_upper <= 1000000):
        return False, 'domain_artifact_upper'
    if not (isinstance(s.cap_index, int) and not isinstance(s.cap_index, bool) and 0 <= s.cap_index <= 1000):
        return False, 'domain_cap_index'
    if not (isinstance(s.holder_delta, int) and not isinstance(s.holder_delta, bool) and 0 <= s.holder_delta <= 1000000):
        return False, 'domain_holder_delta'
    if not (isinstance(s.holder_posted, int) and not isinstance(s.holder_posted, bool) and 0 <= s.holder_posted <= 1000000):
        return False, 'domain_holder_posted'
    if not (isinstance(s.n_notional, int) and not isinstance(s.n_notional, bool) and 0 <= s.n_notional <= 1000):
        return False, 'domain_n_notional'
    if not (s.phase in ('Idle', 'Compiled', 'Settled')):
        return False, 'domain_phase'
    if not (isinstance(s.source_upper, int) and not isinstance(s.source_upper, bool) and 0 <= s.source_upper <= 1000):
        return False, 'domain_source_upper'
    if not (isinstance(s.witness_final, int) and not isinstance(s.witness_final, bool) and 0 <= s.witness_final <= 1000):
        return False, 'domain_witness_final'
    if not (isinstance(s.writer_delta, int) and not isinstance(s.writer_delta, bool) and -1000000 <= s.writer_delta <= 0):
        return False, 'domain_writer_delta'
    if not (isinstance(s.writer_posted, int) and not isinstance(s.writer_posted, bool) and 0 <= s.writer_posted <= 1000000):
        return False, 'domain_writer_posted'
    if not ((True if ('Idle' == s.phase) else (0 == s.artifact_lower))):
        return False, 'inv_compiled_lower_is_zero'
    if not ((True if ('Idle' == s.phase) else (((s.source_upper if (s.source_upper <= s.cap_index) else s.cap_index) * s.n_notional) == s.artifact_upper))):
        return False, 'inv_compiled_upper_matches_n_min_source_cap'
    if not (((0 == (s.holder_delta + s.writer_delta)) if ('Settled' == s.phase) else True)):
        return False, 'inv_delta_conservation'
    if not ((((s.holder_delta + s.holder_posted) >= 0) if ('Settled' == s.phase) else True)):
        return False, 'inv_holder_solvent_after_accept'
    if not (((s.holder_delta <= s.artifact_upper) if ('Settled' == s.phase) else True)):
        return False, 'inv_settled_holder_delta_bounded'
    if not (((s.holder_delta >= 0) if ('Settled' == s.phase) else True)):
        return False, 'inv_settled_holder_delta_nonnegative'
    if not ((((0 - s.holder_delta) == s.writer_delta) if ('Settled' == s.phase) else True)):
        return False, 'inv_settled_writer_is_neg_holder'
    if not ((((s.writer_delta + s.writer_posted) >= 0) if ('Settled' == s.phase) else True)):
        return False, 'inv_writer_solvent_after_accept'
    return True, None


def step(s: State, cmd: Command) -> StepResult:
    """Execute a step. Returns StepResult."""
    # Check pre-state invariants
    ok, failed = check_invariants(s)
    if not ok:
        return StepResult(ok=False, error=f'pre-invariant violated: {failed}')

    if cmd.tag == 'compile_fee_note':
        if 'n_in' not in cmd.args or not (isinstance(cmd.args['n_in'], int) and not isinstance(cmd.args['n_in'], bool) and 0 <= cmd.args['n_in'] <= 1000):
            return StepResult(ok=False, error='invalid param n_in')
        if 'cap_in' not in cmd.args or not (isinstance(cmd.args['cap_in'], int) and not isinstance(cmd.args['cap_in'], bool) and 0 <= cmd.args['cap_in'] <= 1000):
            return StepResult(ok=False, error='invalid param cap_in')
        if 'source_upper_in' not in cmd.args or not (isinstance(cmd.args['source_upper_in'], int) and not isinstance(cmd.args['source_upper_in'], bool) and 0 <= cmd.args['source_upper_in'] <= 1000):
            return StepResult(ok=False, error='invalid param source_upper_in')
        if not (('Idle' == s.phase)):
            return StepResult(ok=False, error='guard failed for compile_fee_note')
        # Compute updates (simultaneous)
        new_state = State(
            artifact_lower=0,
            artifact_upper=((cmd.args['source_upper_in'] if (cmd.args['source_upper_in'] <= cmd.args['cap_in']) else cmd.args['cap_in']) * cmd.args['n_in']),
            cap_index=cmd.args['cap_in'],
            holder_delta=s.holder_delta,
            holder_posted=s.holder_posted,
            n_notional=cmd.args['n_in'],
            phase='Compiled',
            source_upper=cmd.args['source_upper_in'],
            witness_final=s.witness_final,
            writer_delta=s.writer_delta,
            writer_posted=s.writer_posted,
        )
        effects = {
            'compiled_upper': ((cmd.args['source_upper_in'] if (cmd.args['source_upper_in'] <= cmd.args['cap_in']) else cmd.args['cap_in']) * cmd.args['n_in']),
            'firev_accept': False,
            'payoff_out': 0,
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    elif cmd.tag == 'firev_accept_and_settle':
        if 'witness_final_in' not in cmd.args or not (isinstance(cmd.args['witness_final_in'], int) and not isinstance(cmd.args['witness_final_in'], bool) and 0 <= cmd.args['witness_final_in'] <= 1000):
            return StepResult(ok=False, error='invalid param witness_final_in')
        if 'holder_posted_in' not in cmd.args or not (isinstance(cmd.args['holder_posted_in'], int) and not isinstance(cmd.args['holder_posted_in'], bool) and 0 <= cmd.args['holder_posted_in'] <= 1000000):
            return StepResult(ok=False, error='invalid param holder_posted_in')
        if 'writer_posted_in' not in cmd.args or not (isinstance(cmd.args['writer_posted_in'], int) and not isinstance(cmd.args['writer_posted_in'], bool) and 0 <= cmd.args['writer_posted_in'] <= 1000000):
            return StepResult(ok=False, error='invalid param writer_posted_in')
        if not (((cmd.args['witness_final_in'] <= s.source_upper) and ('Compiled' == s.phase) and (cmd.args['holder_posted_in'] >= s.artifact_lower) and (cmd.args['writer_posted_in'] >= s.artifact_upper))):
            return StepResult(ok=False, error='guard failed for firev_accept_and_settle')
        # Compute updates (simultaneous)
        new_state = State(
            artifact_lower=s.artifact_lower,
            artifact_upper=s.artifact_upper,
            cap_index=s.cap_index,
            holder_delta=((cmd.args['witness_final_in'] if (cmd.args['witness_final_in'] <= s.cap_index) else s.cap_index) * s.n_notional),
            holder_posted=cmd.args['holder_posted_in'],
            n_notional=s.n_notional,
            phase='Settled',
            source_upper=s.source_upper,
            witness_final=cmd.args['witness_final_in'],
            writer_delta=(0 - ((cmd.args['witness_final_in'] if (cmd.args['witness_final_in'] <= s.cap_index) else s.cap_index) * s.n_notional)),
            writer_posted=cmd.args['writer_posted_in'],
        )
        effects = {
            'compiled_upper': new_state.artifact_upper,
            'firev_accept': True,
            'payoff_out': new_state.holder_delta,
        }
        ok, failed = check_invariants(new_state)
        if not ok:
            return StepResult(ok=False, error=f'post-invariant violated: {failed}')
        return StepResult(ok=True, state=new_state, effects=effects)
    else:
        return StepResult(ok=False, error=f'unknown action: {cmd.tag}')


# === Hypothesis test scaffolding ===
# Uncomment and install hypothesis to use property-based testing

# from hypothesis import given, strategies as st
# from hypothesis.stateful import RuleBasedStateMachine, rule, initialize
#
# class ModelStateMachine(RuleBasedStateMachine):
#     def __init__(self):
#         super().__init__()
#         self.state = init_state()
#
#     @initialize()
#     def init(self):
#         self.state = init_state()
#         ok, _ = check_invariants(self.state)
#         assert ok, 'init violates invariants'
#
#     # @rule(n_in=st.integers(), cap_in=st.integers(), source_upper_in=st.integers())
#     # def compile_fee_note(self, n_in, cap_in, source_upper_in):
#     #     cmd = Command(tag='compile_fee_note', args={'n_in': n_in, 'cap_in': cap_in, 'source_upper_in': source_upper_in})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
#     # @rule(witness_final_in=st.integers(), holder_posted_in=st.integers(), writer_posted_in=st.integers())
#     # def firev_accept_and_settle(self, witness_final_in, holder_posted_in, writer_posted_in):
#     #     cmd = Command(tag='firev_accept_and_settle', args={'witness_final_in': witness_final_in, 'holder_posted_in': holder_posted_in, 'writer_posted_in': writer_posted_in})
#     #     result = step(self.state, cmd)
#     #     if result.ok:
#     #         self.state = result.state
#
# TestModel = ModelStateMachine.TestCase


def replay_trace(commands: list[tuple[str, dict[str, Any]]]) -> list[StepResult]:
    """Replay a trace of commands and return results."""
    results: list[StepResult] = []
    s = init_state()
    for tag, args in commands:
        cmd = Command(tag=tag, args=args)
        result = step(s, cmd)
        results.append(result)
        if result.ok and result.state is not None:
            s = result.state
        else:
            break
    return results


if __name__ == '__main__':
    # Quick sanity check
    s0 = init_state()
    ok, failed = check_invariants(s0)
    print(f'Initial state: {s0}')
    print(f'Invariants OK: {ok}')
    if not ok:
        print(f'  Failed: {failed}')
