import Proofs.BatchAuctionCanonical
import Proofs.SettlementAlgebra
import Proofs.BatchOptimality
import Proofs.CPMMInvariants
import Proofs.CPMMSettlement
import Proofs.BatchCPMMUnification
import Proofs.SettlementCanonicalExecution
import Proofs.SettlementMechanism
import Proofs.PokayokeSafety
import Proofs.PerpEpochSafety
import Proofs.PerpMechanismDesign
import Proofs.PerpGameTheory
import Proofs.PerpProtocolSafety
import Proofs.CubicSumRatio
import Proofs.CpmmSwapV8ExactOutMinimality
import Proofs.ImpossibilityTheorem
import Proofs.QuarticBlendK
import Proofs.QuarticBlendSwapSpec
import Proofs.TauSafeMul32
import Proofs.PerpFundingRateSafety
import Proofs.PerpCascadeSafety
import Proofs.PerpInsuranceSafety
import Proofs.PerpIntegerBridge
import Proofs.FundingRateMarketSafety
import Proofs.ILFuturesSafety
import Proofs.VolatilityTierSafety
import Proofs.CurveSelectionSafety
import Proofs.ZenoDEXNonces
import Proofs.ZenoDEXRoutingArgmin
import Proofs.ZenoDEXExactInTrueKeyWinner
import Proofs.ZenoDEXExactOutManyPoolPathWitnessCanonicalCandidateMinimum
import Proofs.ZenoDEXExactOutManyPoolCpmmOrderedQuotedPathCompleteness
import Proofs.ZenoDEXExactOutManyPoolCpmmQuotedPathQuoteStreamCompleteness
import Proofs.ZenoDEXExactOutManyPoolQuotedPathQuoteStreamCompleteness
import Proofs.ZenoDEXExactOutManyPoolRepairedAdvisoryQuotePacket
import Proofs.ZenoDEXExactOutManyPoolRepairedFullDomainCertifiedPacket
import Proofs.ZenoDEXExactOutManyPoolRepairedPrefilterSemanticBridge
import Proofs.ZenoDEXRounding
import Proofs.BatchApproximation
import Proofs.ExactOutAdaptiveGate
import Proofs.MobiusCPMMRoutingBounds
import Proofs.PiecewiseEnvelopeNoOverdelivery
import Proofs.PiecewiseEnvelopeNoOverdeliveryV2
import Proofs.PiecewiseEnvelopeParametric
import Proofs.FeeCeilDecomposition
import Proofs.ZenoDEXSTierDisasterMath
import Proofs.ZenoDEXYieldLikeFundingSafety
import Proofs.CBCDisasterStateRefactors
import Proofs.CertifiedFinancialMathObjects
import Proofs.CALCoreSoundness
import Proofs.ZenoPayoffLanguage
import Proofs.ZenoDEXSettlementAttestationAllowlist

/-!
Proofs library root.

This module exists so `lake build` compiles the full set of proof artifacts under `Proofs/`.
-/
