import Proofs
#check AntiFragmentation.anti_fragmentation_general
#check FeeAwareAntiFragmentation.fee_aware_anti_fragmentation
#check OppositeDirectionNoncommutativity.generic_path_noncommutativity
#check FeeAwareBatchKGap.feeBatch_K_gap_sum
#check CPMMOutputMonotonicity.swapOut_mono_y
