(** Differential test: the OCaml spec must match the Python-derived TSV vectors.

    Vectors are generated by [tools/runtime/ocaml_spec_vectors.py] from the
    authoritative Python runtime and committed under [vectors/]. dune copies them
    next to the test (see the [(deps (glob_files vectors/*.tsv))] stanza), so they
    are read by relative path. Exits non-zero on any mismatch. *)

let failures = ref 0

let fail fmt = Printf.ksprintf (fun s -> incr failures; print_string ("FAIL: " ^ s ^ "\n")) fmt

let read_data_lines path =
  let ic = open_in path in
  let rec loop acc =
    match input_line ic with
    | line -> loop (line :: acc)
    | exception End_of_file ->
      close_in ic;
      List.rev acc
  in
  match loop [] with
  | _header :: rows -> rows
  | [] -> []

let cols line = Array.of_list (String.split_on_char '\t' line)

let check_fee_router () =
  let rows = read_data_lines "vectors/fee_router.tsv" in
  if rows = [] then fail "fee_router.tsv has no data rows";
  List.iter
    (fun line ->
      let f = cols line in
      let amount = int_of_string f.(1) in
      let buyburn_bps = int_of_string f.(2) in
      let stakers_bps = int_of_string f.(3) in
      let reserve_bps = int_of_string f.(4) in
      let hosts_bps = int_of_string f.(5) in
      let eb = int_of_string f.(6) in
      let es = int_of_string f.(7) in
      let er = int_of_string f.(8) in
      let eh = int_of_string f.(9) in
      let ed = int_of_string f.(10) in
      let b, s, r, h, d =
        Runtime_spec.Fee_router.route ~amount ~buyburn_bps ~stakers_bps ~reserve_bps ~hosts_bps
      in
      if not (b = eb && s = es && r = er && h = eh && d = ed) then
        fail "fee_router amount=%d: got (%d,%d,%d,%d,%d) want (%d,%d,%d,%d,%d)" amount b s r h d eb
          es er eh ed;
      if b + s + r + h + d <> amount then fail "fee_router amount=%d: conservation broken" amount)
    rows

let check_replay_guard () =
  let rows = read_data_lines "vectors/replay_guard.tsv" in
  if rows = [] then fail "replay_guard.tsv has no data rows";
  List.iter
    (fun line ->
      let f = cols line in
      let last = int_of_string f.(0) in
      let nonce = int_of_string f.(1) in
      let want_code = f.(3) in
      let got = Runtime_spec.Replay_guard.admit ~last ~nonce in
      if got <> want_code then
        fail "replay_guard last=%d nonce=%d: got %s want %s" last nonce got want_code)
    rows

let () =
  check_fee_router ();
  check_replay_guard ();
  if !failures > 0 then (
    Printf.printf "%d vector mismatch(es)\n" !failures;
    exit 1)
  else print_string "OCaml spec oracle: all vectors match Python authority\n"
