#!/usr/bin/env python3
"""Generate the source-bound, research-only O005 semantic-resolution registry."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Final

try:
    from tools.build_m6_normative_requirements_v1 import (
        ShellRejectV1,
        _atomic_replace_regular_file_v1,
        _read_bounded_regular_file_v1,
        _require_inert_path_v1,
    )
    from tools.m6_o005_semantic_resolutions_v1 import (
        MAX_ARTIFACT_BYTES_V1,
        SOURCE_ARTIFACT_PATH_V1,
        SemanticResolutionRejectV1,
        build_semantic_resolution_artifact_v1,
    )
except ModuleNotFoundError:
    from build_m6_normative_requirements_v1 import (  # type: ignore[no-redef]
        ShellRejectV1,
        _atomic_replace_regular_file_v1,
        _read_bounded_regular_file_v1,
        _require_inert_path_v1,
    )
    from m6_o005_semantic_resolutions_v1 import (  # type: ignore[no-redef]
        MAX_ARTIFACT_BYTES_V1,
        SOURCE_ARTIFACT_PATH_V1,
        SemanticResolutionRejectV1,
        build_semantic_resolution_artifact_v1,
    )


REPO_ROOT: Final = Path(__file__).resolve().parents[1]
JSON_OUTPUT: Final = Path("docs/research/M6_O005_SEMANTIC_RESOLUTIONS_V1.json")


def load_o005_source_bytes_v1(root: Path | str) -> bytes:
    """Acquire exact bounded source bytes for internal parsing by the core."""

    inert_root = _require_inert_path_v1(root, "O005 source root")
    return _read_bounded_regular_file_v1(
        inert_root / SOURCE_ARTIFACT_PATH_V1,
        MAX_ARTIFACT_BYTES_V1,
        "O005 requirements artifact",
    )


def build_artifact_v1(root: Path | str) -> bytes:
    """Construct exact generated bytes from the current source-bound snapshot."""

    return build_semantic_resolution_artifact_v1(load_o005_source_bytes_v1(root))


def _build_report_v1(
    ok: bool,
    actual_artifact: bytes | None,
    expected_artifact: bytes | None,
    finding: object | None,
) -> dict[str, object]:
    report: dict[str, object] = {
        "artifact_sha256": (
            hashlib.sha256(actual_artifact).hexdigest() if actual_artifact is not None else ""
        ),
        "closed_value_movement_gates": 0,
        "finding": finding,
        "manifest_complete": False,
        "ok": ok,
        "production_authority": "NONE",
        "release_eligible": False,
        "requirements_closed": False,
        "schema": "zenodex/m6-o005-semantic-resolutions-build/v1",
        "semantic_closure_complete": False,
        "settlement_authority": "NONE",
        "expected_artifact_sha256": (
            hashlib.sha256(expected_artifact).hexdigest() if expected_artifact is not None else ""
        ),
        "value_movement_claim_allowed": False,
    }
    return report


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    expected_artifact: bytes | None = None
    actual_artifact: bytes | None = None
    try:
        expected_artifact = build_artifact_v1(args.root)
        output = args.root / JSON_OUTPUT
        if args.check:
            actual_artifact = _read_bounded_regular_file_v1(
                output,
                MAX_ARTIFACT_BYTES_V1,
                "O005 semantic-resolution artifact",
            )
            ok = actual_artifact == expected_artifact
            finding = (
                None
                if ok
                else {
                    "code": "GENERATED_ARTIFACT_DRIFT",
                    "detail": "actual bytes do not equal source-bound generated bytes",
                    "path": str(JSON_OUTPUT),
                }
            )
            print(
                json.dumps(
                    _build_report_v1(ok, actual_artifact, expected_artifact, finding),
                    sort_keys=True,
                )
            )
            return 0 if ok else 1
        _atomic_replace_regular_file_v1(output, expected_artifact)
        print(
            json.dumps(
                _build_report_v1(True, expected_artifact, expected_artifact, None), sort_keys=True
            )
        )
        return 0
    except (SemanticResolutionRejectV1, ShellRejectV1) as exc:
        finding = {"code": exc.code, "detail": exc.detail, "path": exc.path}
        print(
            json.dumps(
                _build_report_v1(False, actual_artifact, expected_artifact, finding), sort_keys=True
            )
        )
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
