//! Cross-language EPOCH-MACHINE differential: replay the scenario fixture
//! (generated by running the scripts through gov_epoch.py and recording every
//! observable — receipt code/surface/digests/pin + params + trajectory +
//! charter + frozen + pending) and assert the Rust `epoch` module reproduces
//! every field at every step. 53 transitions covering all 17 receipt codes
//! and all three surface-gate labels.

use std::path::PathBuf;

use zenodex_governance_gate::epoch::{
    self, EpochState, PendingRevision, Surface, SURFACE_COUNT,
};

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../tests/tau_specs/governance/fixtures/gov_epoch_scenarios.json")
}

fn as_u16(v: &serde_json::Value) -> u16 {
    u16::try_from(v.as_u64().expect("u16 field")).expect("fits u16")
}

fn params_arr(obj: &serde_json::Value) -> [u16; SURFACE_COUNT] {
    let map = obj.as_object().expect("params object");
    let mut out = [0_u16; SURFACE_COUNT];
    assert_eq!(map.len(), SURFACE_COUNT, "params must cover all surfaces");
    for (k, v) in map {
        let s = Surface::from_name(k).expect("known surface");
        out[s as usize] = as_u16(v);
    }
    out
}

fn deltas_of(obj: &serde_json::Value) -> ([i32; SURFACE_COUNT], [bool; SURFACE_COUNT]) {
    let map = obj.as_object().expect("deltas object");
    let mut deltas = [0_i32; SURFACE_COUNT];
    let mut touched = [false; SURFACE_COUNT];
    for (k, v) in map {
        let s = Surface::from_name(k).expect("known surface");
        deltas[s as usize] = i32::try_from(v.as_i64().expect("int delta")).expect("fits i32");
        touched[s as usize] = true;
    }
    (deltas, touched)
}

fn pin_bytes(hex_pin: &str) -> [u8; 32] {
    let raw = hex::decode(hex_pin).expect("hex pin");
    raw.try_into().expect("32-byte pin")
}

/// Apply one fixture op; returns (new_state, observed receipt fields or None for genesis).
fn step(
    state: Option<EpochState>,
    op: &str,
    args: &serde_json::Value,
) -> (EpochState, Option<epoch::EpochReceipt>) {
    match op {
        "genesis" => {
            let params = params_arr(&args["params"]);
            (epoch::genesis_state(params, as_u16(&args["epoch"])), None)
        }
        "propose" => {
            let s = state.expect("state");
            let (d, t) = deltas_of(&args["deltas"]);
            let (new, r) =
                epoch::propose_revision(&s, &d, &t, as_u16(&args["now"])).expect("in-domain");
            (new, Some(r))
        }
        "veto" => {
            let s = state.expect("state");
            let (new, r) = epoch::veto_pending(&s, as_u16(&args["now"]));
            (new, Some(r))
        }
        "apply" => {
            let s = state.expect("state");
            let (new, r) = epoch::apply_pending(&s, as_u16(&args["now"]));
            (new, Some(r))
        }
        "renew" => {
            let s = state.expect("state");
            let pin = pin_bytes(args["pin"].as_str().expect("pin"));
            let (new, r) = epoch::renew_charter(&s, as_u16(&args["now"]), as_u16(&args["ttl"]), pin)
                .expect("legal ttl");
            (new, Some(r))
        }
        "revoke" => {
            let s = state.expect("state");
            let (new, r) = epoch::revoke_charter(&s, as_u16(&args["now"]));
            (new, Some(r))
        }
        "freeze" | "unfreeze" => {
            let s = state.expect("state");
            let (new, r) = epoch::set_frozen(&s, op == "freeze", as_u16(&args["now"]));
            (new, Some(r))
        }
        other => panic!("unknown op {other}"),
    }
}

fn assert_state_matches(ctx: &str, state: &EpochState, expected: &serde_json::Value) {
    let exp_params = params_arr(&expected["params"]);
    assert_eq!(state.params, exp_params, "{ctx}: params");
    let traj = expected["traj"].as_object().expect("traj object");
    for (k, t) in traj {
        let s = Surface::from_name(k).expect("known surface");
        let got = state.traj[s as usize];
        assert_eq!(got.last_revision_epoch, as_u16(&t["last_revision_epoch"]), "{ctx}: {k} last_rev");
        assert_eq!(got.window_start_epoch, as_u16(&t["window_start_epoch"]), "{ctx}: {k} window");
        assert_eq!(got.drift_used, as_u16(&t["drift_used"]), "{ctx}: {k} drift_used");
    }
    match (&state.charter, expected["charter"].is_null()) {
        (None, true) => {}
        (Some(c), false) => {
            let e = &expected["charter"];
            assert_eq!(c.granted_epoch, as_u16(&e["granted_epoch"]), "{ctx}: charter granted");
            assert_eq!(c.ttl, as_u16(&e["ttl"]), "{ctx}: charter ttl");
            assert_eq!(c.revoked, e["revoked"].as_bool().expect("bool"), "{ctx}: revoked");
            assert_eq!(hex::encode(c.policy_pin), e["policy_pin"].as_str().expect("pin"),
                "{ctx}: charter pin");
        }
        (got, _) => panic!("{ctx}: charter presence mismatch (rust={got:?})"),
    }
    assert_eq!(state.frozen, expected["frozen"].as_bool().expect("bool"), "{ctx}: frozen");
    match (&state.pending, expected["pending"].is_null()) {
        (None, true) => {}
        (Some(p), false) => {
            let e = &expected["pending"];
            assert_eq!(p.proposed_epoch, as_u16(&e["proposed_epoch"]), "{ctx}: pending epoch");
            let (exp_d, exp_t) = deltas_of(&e["deltas"]);
            let norm: PendingRevision = PendingRevision {
                deltas: exp_d,
                touched: exp_t,
                proposed_epoch: p.proposed_epoch,
            };
            assert_eq!(p.deltas, norm.deltas, "{ctx}: pending deltas");
            assert_eq!(p.touched, norm.touched, "{ctx}: pending touched");
        }
        (got, _) => panic!("{ctx}: pending presence mismatch (rust={got:?})"),
    }
}

#[test]
fn rust_epoch_machine_replays_python_scenarios() {
    let raw = std::fs::read_to_string(fixture_path()).expect("scenario fixture present");
    let doc: serde_json::Value = serde_json::from_str(&raw).expect("fixture parses");
    let scenarios = doc["scenarios"].as_array().expect("scenarios");
    assert!(scenarios.len() >= 3);
    let mut steps_total = 0_usize;
    for scenario in scenarios {
        let name = scenario["name"].as_str().expect("name");
        let mut state: Option<EpochState> = None;
        for (i, rec) in scenario["steps"].as_array().expect("steps").iter().enumerate() {
            let ctx = format!("{name}#{i} {}", rec["op"].as_str().unwrap_or("?"));
            let (new, got_receipt) = step(state, rec["op"].as_str().expect("op"), &rec["args"]);
            if let Some(exp) = rec.get("receipt") {
                let r = got_receipt.as_ref().unwrap_or_else(|| panic!("{ctx}: receipt expected"));
                assert_eq!(r.code.as_str(), exp["code"].as_str().expect("code"), "{ctx}: code");
                assert_eq!(r.epoch, as_u16(&exp["epoch"]), "{ctx}: epoch");
                let exp_surface = exp["surface"].as_str();
                assert_eq!(r.surface, exp_surface, "{ctx}: surface");
                assert_eq!(r.digest_before, exp["digest_before"].as_str().expect("d0"),
                    "{ctx}: digest_before");
                assert_eq!(r.digest_after, exp["digest_after"].as_str().expect("d1"),
                    "{ctx}: digest_after");
                let exp_pin = exp["policy_pin"].as_str();
                assert_eq!(r.policy_pin.map(hex::encode).as_deref(), exp_pin, "{ctx}: pin");
            }
            assert_state_matches(&ctx, &new, &rec["state"]);
            state = Some(new);
            steps_total += 1;
        }
    }
    assert!(steps_total >= 50, "fixture unexpectedly small: {steps_total}");
}
