"""Closed JSON input schema and deterministic Tau stream export."""

from __future__ import annotations

import json
import re
from typing import Any

from .compiler import CompiledRepair
from .models import Contract, Requirement
from .terms import Term, constant, join, meet, negate, variable, xor

SCHEMA = "tau-composition/contract-v1"


def _object(value: object, keys: set[str]) -> dict[str, Any]:
    if type(value) is not dict or set(value) != keys:
        raise ValueError("closed_object_shape")
    return value


def _term(value: object, budget: list[int], depth: int = 0) -> Term:
    budget[0] -= 1
    if budget[0] < 0 or depth > 48:
        raise ValueError("term_budget")
    if type(value) is not dict:
        raise ValueError("term_object")
    kind = value.get("kind")
    if kind in {"constant", "variable"}:
        node = _object(value, {"kind", "value"})
        return constant(node["value"]) if kind == "constant" else variable(node["value"])
    node = _object(value, {"kind", "operands"})
    operands = node["operands"]
    if type(operands) is not list or not 1 <= len(operands) <= 128:
        raise ValueError("term_operand_bound")
    children = tuple(_term(item, budget, depth + 1) for item in operands)
    return _operation(kind, children)


def _operation(kind: object, children: tuple[Term, ...]) -> Term:
    if kind == "negate" and len(children) == 1:
        return negate(children[0])
    if kind == "xor" and len(children) == 2:
        return xor(*children)
    if kind == "meet" and len(children) >= 2:
        return meet(*children)
    if kind == "join" and len(children) >= 2:
        return join(*children)
    raise ValueError("term_operator_or_arity")


def _unique_object(pairs: list[tuple[str, object]]) -> dict[str, object]:
    result: dict[str, object] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate_json_key")
        result[key] = value
    return result


def decode_contract(text: str) -> Contract:
    if len(text.encode("utf-8")) > 256_000:
        raise ValueError("contract_byte_bound")
    data = _object(json.loads(text, object_pairs_hook=_unique_object), {
        "schema", "name", "environment", "controls", "requirements",
    })
    if data["schema"] != SCHEMA:
        raise ValueError("contract_schema")
    if any(type(data[key]) is not list for key in ("environment", "controls", "requirements")):
        raise ValueError("contract_list_shape")
    budget = [4096]
    requirements = []
    for raw in data["requirements"]:
        item = _object(raw, {"name", "residual"})
        requirements.append(Requirement(item["name"], _term(item["residual"], budget)))
    return Contract(data["name"], tuple(data["environment"]), tuple(data["controls"]), tuple(requirements))


def encode_contract(contract: Contract) -> dict[str, object]:
    return {
        "schema": SCHEMA, "name": contract.name,
        "environment": list(contract.environment), "controls": list(contract.controls),
        "requirements": [{"name": item.name, "residual": item.residual.canonical_data()}
                         for item in contract.requirements],
    }


def export_tau(compiled: CompiledRepair) -> str:
    """Generate a total, deterministic proposal transducer from the checked map.

    Each supplied bit is a host observation or proposed action. The output has
    no authorization, balance, proof, or Tau Net submission effect.
    """
    names = compiled.contract.environment + compiled.contract.controls
    symbols = {name: f"v{index}" for index, name in enumerate(names)}
    lines = [
        "# Original Tau proposal controller; generated by tools/tau_composition.py.",
        "# Summary: repair Boolean proposals while retaining every valid proposal.",
        "# Assumptions: exact Boolean host observations; authority checked separately.",
        "# Guarantee: output flags satisfy the input contract; no external effects.",
    ]
    lines.extend(f"# i{index + 1}: {name} (sbf)" for index, name in enumerate(names))
    outputs = []
    stream_slots = {name: index + 1 for index, name in enumerate(names)}
    for index, (name, term) in enumerate(compiled.repair.assignments):
        lines.append(f"# o{index + 1}: proposed {name} (sbf)")
        # Names in the output are generator-owned, never caller-supplied Tau.
        body = term.to_tau(symbols)
        used = tuple(name for name in names if name in term.variables()) or names[:1]
        args = ", ".join(symbols[name] for name in used)
        inputs = ", ".join(f"i{stream_slots[name]}[t]:sbf" for name in used)
        lines.append(f"repair{index}({args}):sbf := {body}.")
        outputs.append(f"(o{index + 1}[t]:sbf = repair{index}({inputs}))")
    lines.append("always (" + " && ".join(outputs) + ").")
    text = "\n".join(lines) + "\n"
    if re.search(r"\bi12\[t\]", text):
        # This is a generic stream artifact, never mislabel it a Tau Net offer.
        lines.insert(1, "# Generic local streams; not a Tau Net rule-offer payload.")
        text = "\n".join(lines) + "\n"
    return text
