[package]
name = "zenodex-zrpf-risc0-v2-leaf-adapter"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
risc0-zkvm = { version = "=3.0.5", default-features = false }
zenodex-zrpf-protocol-v3 = { path = "../../../zrpf_protocol/protocol", default-features = false }
zenodex-zrpf-risc0-shared = { path = "../../shared", default-features = false }

[[bin]]
name = "zenodex-zrpf-risc0-v2-leaf-adapter"
path = "src/main.rs"
test = false
bench = false
