[package]
name = "zenodex-perps-margin-module-guest"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
risc0-zkvm = { version = "=3.0.6", default-features = false, features = ["std"] }
zenodex-perps-margin-module-risc0-shared = { path = "../../shared" }

[[bin]]
name = "zenodex-perps-margin-module-guest"
path = "src/main.rs"
test = false
bench = false
